//! Windows console event handling for clai-wrap.
//!
//! This module provides console event handling for the PTY wrapper on Windows using
//! the Windows Console API. It manages Ctrl-C, Ctrl-Break, and other console events.
//!
//! # Events Handled
//!
//! - **Ctrl-C (`CTRL_C_EVENT`)**: Forward to child, clean shutdown
//! - **Ctrl-Break (`CTRL_BREAK_EVENT`)**: Immediate termination
//! - **Close Button (`CTRL_CLOSE_EVENT`)**: Clean shutdown
//! - **Logoff (`CTRL_LOGOFF_EVENT`)**: Clean shutdown
//! - **Shutdown (`CTRL_SHUTDOWN_EVENT`)**: Clean shutdown
//!
//! # Console Resize
//!
//! Console resize events are handled separately via `portable-pty` and the console
//! buffer APIs, not through `SetConsoleCtrlHandler`. See the `resize` module for
//! resize handling.

#![cfg(windows)]

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc::{self, Receiver, SendError, Sender, TryRecvError};
use std::sync::{Arc, Mutex, OnceLock};

use windows_sys::Win32::Foundation::{BOOL, FALSE, TRUE};
use windows_sys::Win32::System::Console::{
    SetConsoleCtrlHandler, CTRL_BREAK_EVENT, CTRL_CLOSE_EVENT, CTRL_C_EVENT, CTRL_LOGOFF_EVENT,
    CTRL_SHUTDOWN_EVENT,
};

/// Global state for the console event handler.
///
/// Windows console handlers are set globally and receive events via a callback function.
/// We use this static to communicate between the callback and our `ConsoleEventHandler`.
static GLOBAL_HANDLER_STATE: OnceLock<Mutex<Option<Sender<ConsoleEvent>>>> = OnceLock::new();

/// Events generated by Windows console event handling.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConsoleEvent {
    /// Ctrl-C was pressed (CTRL_C_EVENT).
    CtrlC,
    /// Ctrl-Break was pressed (CTRL_BREAK_EVENT).
    CtrlBreak,
    /// Console window close button was clicked (CTRL_CLOSE_EVENT).
    Close,
    /// User is logging off (CTRL_LOGOFF_EVENT).
    Logoff,
    /// System is shutting down (CTRL_SHUTDOWN_EVENT).
    Shutdown,
}

impl ConsoleEvent {
    /// Returns true if this event represents an immediate termination request.
    ///
    /// Ctrl-Break and system shutdown events typically require immediate response.
    #[must_use]
    pub const fn is_immediate(&self) -> bool {
        matches!(self, Self::CtrlBreak | Self::Shutdown)
    }

    /// Returns true if this event should trigger a graceful shutdown.
    #[must_use]
    pub const fn should_shutdown(&self) -> bool {
        matches!(
            self,
            Self::CtrlBreak | Self::Close | Self::Logoff | Self::Shutdown
        )
    }
}

/// Errors that can occur during console event handling.
#[derive(Debug, thiserror::Error)]
pub enum ConsoleEventError {
    /// Failed to register console control handler.
    #[error("failed to register console control handler")]
    Registration,

    /// Failed to unregister console control handler.
    #[error("failed to unregister console control handler")]
    Unregistration,

    /// Handler is already registered (only one handler can be active).
    #[error("console event handler is already registered")]
    AlreadyRegistered,

    /// Failed to send console event.
    #[error("failed to send console event")]
    SendError,

    /// Event receiver disconnected.
    #[error("event receiver disconnected")]
    ReceiverDisconnected,
}

impl<T> From<SendError<T>> for ConsoleEventError {
    fn from(_: SendError<T>) -> Self {
        Self::SendError
    }
}

/// Manages Windows console event handling for the PTY wrapper.
///
/// This struct sets up a console control handler on creation and removes it on drop.
/// It provides a channel-based interface for receiving console events.
///
/// # Platform-Specific
///
/// This type is only available on Windows platforms (`#[cfg(windows)]`).
///
/// # Example
///
/// ```no_run
/// use clai_wrap::windows::console_events::{ConsoleEventHandler, ConsoleEvent};
///
/// let handler = ConsoleEventHandler::new().expect("Failed to set up console handler");
///
/// // In your event loop:
/// match handler.try_recv() {
///     Ok(Some(ConsoleEvent::CtrlC)) => {
///         // Handle Ctrl-C: forward to child or clean shutdown
///     }
///     Ok(Some(ConsoleEvent::Close)) => {
///         // Handle window close: restore terminal state, shutdown
///     }
///     Ok(Some(event)) if event.should_shutdown() => {
///         // Handle other shutdown events
///     }
///     _ => {}
/// }
/// ```
pub struct ConsoleEventHandler {
    /// Channel receiver for console events.
    event_receiver: Receiver<ConsoleEvent>,

    /// Flag indicating whether the handler is active.
    active: Arc<AtomicBool>,
}

impl ConsoleEventHandler {
    /// Creates a new `ConsoleEventHandler` and installs the console control handler.
    ///
    /// Only one `ConsoleEventHandler` can be active at a time. Creating a second
    /// handler while one is already active will return an error.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - A handler is already registered
    /// - The Windows API call to `SetConsoleCtrlHandler` fails
    pub fn new() -> Result<Self, ConsoleEventError> {
        let (tx, rx) = mpsc::channel();

        // Initialize the global state if not already done
        let global_state = GLOBAL_HANDLER_STATE.get_or_init(|| Mutex::new(None));

        // Try to set our sender as the active handler
        {
            let mut guard = global_state
                .lock()
                .map_err(|_| ConsoleEventError::AlreadyRegistered)?;

            if guard.is_some() {
                return Err(ConsoleEventError::AlreadyRegistered);
            }

            *guard = Some(tx);
        }

        // Register the console control handler
        // SAFETY: We're calling a Windows API function with a valid function pointer.
        // The handler function is safe and doesn't access any invalid memory.
        let result = unsafe { SetConsoleCtrlHandler(Some(console_ctrl_handler), TRUE) };

        if result == FALSE {
            // Clean up the global state on failure
            if let Ok(mut guard) = global_state.lock() {
                *guard = None;
            }
            return Err(ConsoleEventError::Registration);
        }

        let active = Arc::new(AtomicBool::new(true));

        Ok(Self {
            event_receiver: rx,
            active,
        })
    }

    /// Returns a reference to the event receiver channel.
    ///
    /// Use this to receive console events in your event loop.
    #[allow(clippy::missing_const_for_fn)]
    pub fn events(&self) -> &Receiver<ConsoleEvent> {
        &self.event_receiver
    }

    /// Tries to receive a console event without blocking.
    ///
    /// # Returns
    ///
    /// - `Ok(Some(event))` if an event is available
    /// - `Ok(None)` if no event is currently available
    /// - `Err(ConsoleEventError)` if the channel is disconnected
    pub fn try_recv(&self) -> Result<Option<ConsoleEvent>, ConsoleEventError> {
        match self.event_receiver.try_recv() {
            Ok(event) => Ok(Some(event)),
            Err(TryRecvError::Empty) => Ok(None),
            Err(TryRecvError::Disconnected) => Err(ConsoleEventError::ReceiverDisconnected),
        }
    }

    /// Blocks until a console event is received.
    ///
    /// # Returns
    ///
    /// - `Ok(event)` when an event is received
    /// - `Err(ConsoleEventError)` if the channel is disconnected
    pub fn recv(&self) -> Result<ConsoleEvent, ConsoleEventError> {
        self.event_receiver
            .recv()
            .map_err(|_| ConsoleEventError::ReceiverDisconnected)
    }

    /// Checks if the handler is still active.
    #[must_use]
    pub fn is_active(&self) -> bool {
        self.active.load(Ordering::SeqCst)
    }
}

impl Drop for ConsoleEventHandler {
    fn drop(&mut self) {
        self.active.store(false, Ordering::SeqCst);

        // Unregister the console control handler
        // SAFETY: We're calling a Windows API function with a valid function pointer.
        // This is the cleanup path and we need to unregister our handler.
        let result = unsafe { SetConsoleCtrlHandler(Some(console_ctrl_handler), FALSE) };

        if result == FALSE {
            // Log but don't panic on unregistration failure
            tracing::warn!("Failed to unregister console control handler");
        }

        // Clear the global sender
        if let Some(global_state) = GLOBAL_HANDLER_STATE.get() {
            if let Ok(mut guard) = global_state.lock() {
                *guard = None;
            }
        }
    }
}

/// Console control handler callback function.
///
/// This function is called by Windows when a console event occurs.
/// It translates the Windows event type to our `ConsoleEvent` enum
/// and sends it through the global channel.
///
/// # Safety
///
/// This function is called from the Windows console subsystem. It must be
/// careful to:
/// - Not panic (would abort the process)
/// - Not block for extended periods
/// - Handle the case where the global sender may be gone
///
/// # Returns
///
/// - `TRUE` if the event was handled
/// - `FALSE` to pass the event to the next handler
#[allow(unsafe_code)]
unsafe extern "system" fn console_ctrl_handler(ctrl_type: u32) -> BOOL {
    let event = match ctrl_type {
        CTRL_C_EVENT => ConsoleEvent::CtrlC,
        CTRL_BREAK_EVENT => ConsoleEvent::CtrlBreak,
        CTRL_CLOSE_EVENT => ConsoleEvent::Close,
        CTRL_LOGOFF_EVENT => ConsoleEvent::Logoff,
        CTRL_SHUTDOWN_EVENT => ConsoleEvent::Shutdown,
        _ => return FALSE, // Unknown event, pass to next handler
    };

    // Try to send the event through the global channel
    if let Some(global_state) = GLOBAL_HANDLER_STATE.get() {
        if let Ok(guard) = global_state.lock() {
            if let Some(sender) = guard.as_ref() {
                // Ignore send errors - the receiver may be gone
                let _ = sender.send(event);
            }
        }
    }

    // For Ctrl-C, we return TRUE to indicate we handled it and prevent
    // the default behavior (process termination)
    // For other events, we also return TRUE to prevent immediate termination
    // and allow our cleanup code to run
    TRUE
}

/// Checks if the current process is running in a console.
///
/// This can be used to determine if console event handling is available.
///
/// # Returns
///
/// `true` if the process has an attached console, `false` otherwise.
#[must_use]
pub fn has_console() -> bool {
    use windows_sys::Win32::System::Console::GetConsoleWindow;

    // SAFETY: GetConsoleWindow is safe to call and doesn't modify any state.
    let hwnd = unsafe { GetConsoleWindow() };
    !hwnd.is_null()
}

#[cfg(all(test, windows))]
mod tests {
    use super::*;
    use std::time::Duration;

    #[test]
    fn test_console_event_is_immediate() {
        assert!(!ConsoleEvent::CtrlC.is_immediate());
        assert!(ConsoleEvent::CtrlBreak.is_immediate());
        assert!(!ConsoleEvent::Close.is_immediate());
        assert!(!ConsoleEvent::Logoff.is_immediate());
        assert!(ConsoleEvent::Shutdown.is_immediate());
    }

    #[test]
    fn test_console_event_should_shutdown() {
        assert!(!ConsoleEvent::CtrlC.should_shutdown());
        assert!(ConsoleEvent::CtrlBreak.should_shutdown());
        assert!(ConsoleEvent::Close.should_shutdown());
        assert!(ConsoleEvent::Logoff.should_shutdown());
        assert!(ConsoleEvent::Shutdown.should_shutdown());
    }

    #[test]
    fn test_console_event_enum_debug() {
        let event = ConsoleEvent::CtrlC;
        let debug_str = format!("{event:?}");
        assert!(debug_str.contains("CtrlC"));
    }

    #[test]
    fn test_console_event_clone() {
        let event = ConsoleEvent::CtrlBreak;
        let cloned = event;
        assert_eq!(event, cloned);
    }

    #[test]
    fn test_console_event_eq() {
        assert_eq!(ConsoleEvent::CtrlC, ConsoleEvent::CtrlC);
        assert_ne!(ConsoleEvent::CtrlC, ConsoleEvent::CtrlBreak);
    }

    #[test]
    fn test_console_event_error_display() {
        let error = ConsoleEventError::Registration;
        let display = format!("{error}");
        assert!(display.contains("register"));

        let error = ConsoleEventError::AlreadyRegistered;
        let display = format!("{error}");
        assert!(display.contains("already registered"));
    }

    #[test]
    fn test_handler_creation_and_drop() {
        // Create handler
        let handler = ConsoleEventHandler::new().expect("Failed to create handler");
        assert!(handler.is_active());

        // Try to create a second handler (should fail)
        let result = ConsoleEventHandler::new();
        assert!(matches!(result, Err(ConsoleEventError::AlreadyRegistered)));

        // Drop the first handler
        drop(handler);

        // Now we should be able to create a new handler
        let handler2 = ConsoleEventHandler::new().expect("Failed to create second handler");
        assert!(handler2.is_active());
        drop(handler2);
    }

    #[test]
    fn test_try_recv_empty() {
        let handler = ConsoleEventHandler::new().expect("Failed to create handler");

        // Initially should be empty
        let result = handler.try_recv();
        assert!(matches!(result, Ok(None)));

        drop(handler);
    }

    #[test]
    fn test_events_receiver() {
        let handler = ConsoleEventHandler::new().expect("Failed to create handler");
        let _receiver = handler.events();

        // Just verify we can get a reference to the receiver
        drop(handler);
    }

    #[test]
    fn test_handler_inactive_after_drop() {
        let handler = ConsoleEventHandler::new().expect("Failed to create handler");
        let active = Arc::clone(&handler.active);
        assert!(active.load(Ordering::SeqCst));

        drop(handler);

        // After drop, the active flag should be false
        assert!(!active.load(Ordering::SeqCst));
    }

    #[test]
    fn test_has_console() {
        // This test verifies the function runs without panicking.
        // The actual result depends on whether tests are run with a console.
        let _result = has_console();
    }

    // Note: We cannot easily test actual Ctrl-C/Ctrl-Break events in unit tests
    // without risking test termination or requiring special permissions.
    // Integration tests with a controlled environment would be needed for that.

    #[test]
    fn test_all_event_variants() {
        // Ensure all event variants are distinct
        let events = [
            ConsoleEvent::CtrlC,
            ConsoleEvent::CtrlBreak,
            ConsoleEvent::Close,
            ConsoleEvent::Logoff,
            ConsoleEvent::Shutdown,
        ];

        for (i, event) in events.iter().enumerate() {
            for (j, other) in events.iter().enumerate() {
                if i == j {
                    assert_eq!(event, other);
                } else {
                    assert_ne!(event, other);
                }
            }
        }
    }

    #[test]
    fn test_console_event_copy() {
        let event = ConsoleEvent::Close;
        let copied: ConsoleEvent = event; // Copy
        assert_eq!(event, copied);
    }

    #[test]
    fn test_error_from_send_error() {
        let (tx, rx) = mpsc::channel::<ConsoleEvent>();
        drop(rx); // Drop receiver to cause send error

        let send_result = tx.send(ConsoleEvent::CtrlC);
        assert!(send_result.is_err());

        let error: ConsoleEventError = send_result.unwrap_err().into();
        assert!(matches!(error, ConsoleEventError::SendError));
    }
}
