# golangci-lint configuration (v2)
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/runger/clai

linters:
  default: none
  # Exclude complexity/length/style linters from test files (table-driven tests are verbose by design)
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocognit
          - funlen
          - dupl
          - lll
          - cyclop
          - gocritic
          - revive
          - gosec
          - maintidx
          - nestif
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional useful linters
    - bodyclose
    - durationcheck
    - errorlint
    - misspell
    - nilerr
    - prealloc
    - unconvert
    # Complexity analysis
    - gocognit
    - cyclop
    - nestif
    - maintidx
    # Length limits
    - lll
    - funlen
    # Duplication detection
    - dupl
    # Style & quality
    - gocritic
    - revive
    - nolintlint
    # Security
    - gosec
    # Architecture
    - depguard
  settings:
    staticcheck:
      checks: ["all"]
    govet:
      enable-all: true
    # Complexity settings
    gocognit:
      min-complexity: 35
    cyclop:
      max-complexity: 22
      package-average: 8.0
    nestif:
      min-complexity: 7
    maintidx:
      under: 18
    # Length limits
    lll:
      line-length: 160
    funlen:
      lines: 100
      statements: 60
    # Duplication threshold
    dupl:
      threshold: 120
    # Style settings
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    # Revive settings
    revive:
      rules: []
    # NOLINT hygiene
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    # Security settings
    gosec:
      excludes:
        - G104  # Unhandled errors - enable errcheck linter to replace this (separate effort)
    # Architecture rules
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: "Deprecated; use io and os packages"
