# ai-terminal.fish - AI Terminal Integration for Fish
# Generated by: ai-terminal init fish
#
# Features:
#   1. Auto-extract suggested commands from output
#   2. Auto-diagnose errors with Claude Code
#
# Configuration (set these BEFORE sourcing):
#   set -gx AI_TERMINAL_AUTO_DIAGNOSE true
#   set -gx AI_TERMINAL_AUTO_EXTRACT true

# ============================================
# Configuration
# ============================================

if not set -q AI_TERMINAL_AUTO_DIAGNOSE
    set -gx AI_TERMINAL_AUTO_DIAGNOSE true
end

if not set -q AI_TERMINAL_AUTO_EXTRACT
    set -gx AI_TERMINAL_AUTO_EXTRACT true
end

if not set -q AI_TERMINAL_CACHE
    set -gx AI_TERMINAL_CACHE "$HOME/.cache/ai-terminal"
end

# Ensure cache directory exists
mkdir -p $AI_TERMINAL_CACHE

# Files
set -g _AI_SUGGEST_FILE "$AI_TERMINAL_CACHE/suggestion"
set -g _AI_LAST_OUTPUT "$AI_TERMINAL_CACHE/last_output"

# ============================================
# Feature 1: Command Suggestion
# ============================================

# Accept suggestion with custom keybinding
function _ai_accept_suggestion
    if test -s $_AI_SUGGEST_FILE
        set -l suggestion (cat $_AI_SUGGEST_FILE)
        if test -n "$suggestion"
            commandline -r $suggestion
            commandline -f end-of-line
            # Clear the suggestion
            echo -n "" > $_AI_SUGGEST_FILE
            return
        end
    end
    # Default behavior: normal tab completion
    commandline -f complete
end

# Bind Alt+Enter to accept suggestion (Tab is used for completions in Fish)
bind \e\r _ai_accept_suggestion

# Clear suggestion with Escape
function _ai_clear_suggestion
    echo -n "" > $_AI_SUGGEST_FILE
    set -g _AI_VOICE_MODE false
    commandline -f repaint
end
bind \e _ai_clear_suggestion

# ============================================
# Feature 3: Voice Mode
# ============================================
# When activated, the next Enter press will run the input through voice conversion

set -g _AI_VOICE_MODE false

function _ai_enter_voice_mode
    set -g _AI_VOICE_MODE true
    commandline -f repaint
end

function _ai_voice_execute
    set -l current_cmd (commandline)

    # Check for ` prefix (voice input marker)
    if string match -q '`*' -- $current_cmd
        and test (string length -- $current_cmd) -gt 1
        # Remove the ` prefix and any leading space
        set -l voice_input (string replace -r '^`\\s*' '' -- $current_cmd)
        commandline -r ""

        echo "🎤 Converting: $voice_input"
        set -l cmd (ai-terminal voice "$voice_input" 2>/dev/null)
        if test -n "$cmd"
            echo "→ $cmd"
            # Put command in buffer for user to review
            commandline -r $cmd
            commandline -f end-of-line
        end
        return
    end

    # Check for explicit voice mode
    if test "$_AI_VOICE_MODE" = "true"
        and test -n "$current_cmd"
        set -g _AI_VOICE_MODE false
        commandline -r ""

        echo "🎤 Converting: $current_cmd"
        set -l cmd (ai-terminal voice "$current_cmd" 2>/dev/null)
        if test -n "$cmd"
            echo "→ $cmd"
            # Put command in buffer for user to review
            commandline -r $cmd
            commandline -f end-of-line
        end
        return
    end

    # Normal execute
    set -g _AI_VOICE_MODE false
    commandline -f execute
end

# Show voice mode indicator in right prompt
function fish_right_prompt
    if test "$_AI_VOICE_MODE" = "true"
        set_color magenta
        echo -n "🎤 Voice mode"
        set_color normal
    else if test -s $_AI_SUGGEST_FILE
        set -l suggestion (cat $_AI_SUGGEST_FILE)
        if test -n "$suggestion"
            set_color brblack
            echo -n "→ $suggestion"
            set_color normal
        end
    end
end

# Bind Ctrl+X Ctrl+V to enter voice mode
bind \cx\cv _ai_enter_voice_mode

# Bind Enter to voice-aware execute
bind \r _ai_voice_execute

# ============================================
# Feature 2: Auto Error Diagnosis
# ============================================

# Track command execution
function _ai_preexec --on-event fish_preexec
    set -g _AI_LAST_CMD $argv[1]
end

# Check result after execution
function _ai_postexec --on-event fish_postexec
    set -l exit_code $status

    # Auto-diagnose if enabled and command failed
    if test "$AI_TERMINAL_AUTO_DIAGNOSE" = "true"
        and test $exit_code -ne 0
        and set -q _AI_LAST_CMD
        and not string match -q "ai-fix*" $_AI_LAST_CMD
        and not string match -q "ai-terminal*" $_AI_LAST_CMD

        echo ""
        set_color yellow
        echo "⚡ Analyzing error..."
        set_color normal

        # Run diagnosis
        ai-terminal diagnose "$_AI_LAST_CMD" "$exit_code" 2>/dev/null
    end

    # Cleanup
    set -e _AI_LAST_CMD
end

# ============================================
# Output Capture (via wrapper function)
# ============================================

# Wrap command execution to capture output
# Usage: run <command> - captures output and extracts suggestions
function run
    # Run command, capture output, pass through ai-terminal extract
    $argv 2>&1 | ai-terminal extract
    return $pipestatus[1]  # Return original command's exit code
end

# ============================================
# Manual Commands
# ============================================

# Manually diagnose last command
function ai-fix
    if test (count $argv) -gt 0
        set cmd $argv[1]
    else
        set cmd (history --max=1)
    end
    ai-terminal diagnose "$cmd" "1"
end

# Ask Claude anything with terminal context
function ai
    if test (count $argv) -eq 0
        echo "Usage: ai \"your question\""
        return 1
    end

    set -l recent_cmds (history --max=5 | string join ';')
    ai-terminal ask --context "$recent_cmds" $argv
end

# Convert voice/natural language to terminal command
function voice
    if test (count $argv) -eq 0
        echo "Usage: voice \"natural language description\""
        return 1
    end

    ai-terminal voice $argv
end

# Toggle auto-diagnose
function ai-toggle
    if test "$AI_TERMINAL_AUTO_DIAGNOSE" = "true"
        set -gx AI_TERMINAL_AUTO_DIAGNOSE false
        echo "Auto-diagnose: OFF"
    else
        set -gx AI_TERMINAL_AUTO_DIAGNOSE true
        echo "Auto-diagnose: ON"
    end
end

# ============================================
# Startup Message
# ============================================

if status is-interactive
    set_color brblack
    echo "🤖 AI Terminal loaded. Commands: ai-fix, ai, voice, ai-toggle, run | ` prefix for voice mode"
    set_color normal
end
