# clai.fish - clai shell integration for Fish
# Generated by: clai init fish
#
# Features:
#   1. Suggestion picker on Tab
#   2. History picker on Up arrow
#   3. Error diagnosis with `run` wrapper (captures output for analysis)
#
# Configuration (set these BEFORE sourcing):
#   set -gx CLAI_AUTO_EXTRACT true

# ============================================
# Configuration
# ============================================

# Export current shell for clai doctor/status detection
set -gx CLAI_CURRENT_SHELL fish

if not set -q CLAI_AUTO_EXTRACT
    set -gx CLAI_AUTO_EXTRACT true
end

if not set -q CLAI_CACHE
    set -gx CLAI_CACHE "$HOME/.cache/clai"
end

if not set -q CLAI_MENU_LIMIT
    set -gx CLAI_MENU_LIMIT 5
end

# Ensure cache directory exists
mkdir -p $CLAI_CACHE

# Files
set -g _AI_SUGGEST_FILE "$CLAI_CACHE/suggestion"
set -g _AI_LAST_OUTPUT "$CLAI_CACHE/last_output"

# Disable native autosuggestions only when clai is enabled
# (leave native suggestions working when CLAI_OFF=1 or session-off)
if test "$CLAI_OFF" != "1"; and not test -f "$CLAI_CACHE/off"
    # Save the user's original autosuggestion setting before overriding
    if not set -q _clai_prev_autosuggestion
        set -g _clai_prev_autosuggestion (set -q fish_autosuggestion_enabled; and echo $fish_autosuggestion_enabled; or echo 1)
    end
    set -g fish_autosuggestion_enabled 0
end

function _clai_session_off
    test -f "$CLAI_CACHE/off"
end

# ============================================
# Feature 1: Command Suggestion
# ============================================

# Accept suggestion with custom keybinding
function _ai_accept_suggestion
    if test -s $_AI_SUGGEST_FILE
        set -l suggestion (cat $_AI_SUGGEST_FILE)
        if test -n "$suggestion"
            commandline -r $suggestion
            commandline -f end-of-line
            # Clear the suggestion
            echo -n "" > $_AI_SUGGEST_FILE
            return
        end
    end
    # Default behavior: normal tab completion
    commandline -f complete
end

# Bind Alt+Enter to accept suggestion (Tab is used for completions in Fish)
bind \e\r _ai_accept_suggestion

# Clear suggestion with Escape
function _ai_clear_suggestion
    echo -n "" > $_AI_SUGGEST_FILE
    set -g _AI_VOICE_MODE false
    commandline -f repaint
end

# Unified Escape handler: cancel picker if active, otherwise clear suggestion
function _clai_escape
    if test "$_CLAI_PICKER_ACTIVE" = "true"
        _clai_picker_cancel
    else
        _ai_clear_suggestion
    end
end
bind \e _clai_escape

# ============================================
# Feature 2a: TUI Picker (clai-picker)
# ============================================
# If clai-picker is on PATH, Up arrow and Alt+H open the full TUI picker.
# Exit codes: 0 = selection, 1 = cancel, 2 = fallback to native history.

function _clai_has_tui_picker
    type -q clai-picker
end

function _clai_tui_picker_open
    if not _clai_has_tui_picker
        commandline -f up-line
        return
    end
    set -l saved_buffer (commandline)
    set -l result (clai-picker history --query=(commandline) --session=$CLAI_SESSION_ID --cwd=$PWD 2>/dev/null)
    set -l exit_code $status
    if test $exit_code -eq 0
        commandline -r -- $result
        commandline -f end-of-line
    else if test $exit_code -eq 2
        commandline -f up-line
        return
    end
    # exit_code 1 = cancel, keep original buffer
    commandline -f repaint
end

# ============================================
# Feature 2b: Suggestion & History Pickers
# ============================================

set -g _CLAI_PICKER_ACTIVE false
set -g _CLAI_PICKER_MODE ""
set -g _CLAI_PICKER_INDEX 1
set -g _CLAI_PICKER_ORIG_BUFFER ""
set -g _CLAI_PICKER_ITEMS
set -g _CLAI_HISTORY_SCOPE session

set -g _CLAI_SUGGESTIONS_ENABLED ""

function _clai_config_enabled
    # Cache the config value on first call to avoid invoking clai on every keypress
    if test -z "$_CLAI_SUGGESTIONS_ENABLED"
        set -g _CLAI_SUGGESTIONS_ENABLED (clai config suggestions.enabled 2>/dev/null)
    end
    if test "$_CLAI_SUGGESTIONS_ENABLED" = "false"
        return 1
    end
    return 0
end

function _clai_history_args
    # Each argument on its own line so fish command-substitution splits correctly
    # (spaces in $PWD would break single-line echo splitting)
    switch $_CLAI_HISTORY_SCOPE
        case session
            echo "--session=$CLAI_SESSION_ID"
        case cwd
            echo "--session=$CLAI_SESSION_ID"
            echo "--cwd=$PWD"
        case global
            echo "--global"
        case '*'
            echo "--session=$CLAI_SESSION_ID"
    end
end

function _clai_dedup
    # Deduplicate a list preserving first-occurrence order
    # Usage: set -l unique (_clai_dedup $items)
    printf '%s\n' $argv | awk '!seen[$0]++'
end

function _clai_picker_load_suggest
    set -l current (commandline)
    set -l items
    if test -n "$current"
        set items (clai suggest --limit $CLAI_MENU_LIMIT "$current" 2>/dev/null | string split '\n')
    else
        set items (clai history --session="$CLAI_SESSION_ID" --limit $CLAI_MENU_LIMIT 2>/dev/null | string split '\n')
    end
    if test (count $items) -eq 0
        return 1
    end
    set -g _CLAI_PICKER_ITEMS (_clai_dedup $items)
    return 0
end

function _clai_picker_load_history
    set -l args (_clai_history_args)
    set -l prefix (commandline)
    set -l items
    if test -n "$prefix"
        set items (clai history $args --limit $CLAI_MENU_LIMIT "$prefix" 2>/dev/null | string split '\n')
    else
        set items (clai history $args --limit $CLAI_MENU_LIMIT 2>/dev/null | string split '\n')
    end
    if test (count $items) -eq 0
        return 1
    end
    set -g _CLAI_PICKER_ITEMS (_clai_dedup $items)
    return 0
end

set -g _CLAI_PICKER_LINE_COUNT 0

function _clai_picker_render
    set -l header "Suggestions"
    if test "$_CLAI_PICKER_MODE" = "history"
        set header "History ($_CLAI_HISTORY_SCOPE)"
    end

    # Build menu lines
    set -l menu_lines "$header (↑↓, Enter, Esc):" "────────────────────────────────"
    set -l i 1
    for item in $_CLAI_PICKER_ITEMS
        if test $i -eq $_CLAI_PICKER_INDEX
            set -a menu_lines " → $item"
        else
            set -a menu_lines "   $item"
        end
        set i (math $i + 1)
    end

    set -g _CLAI_PICKER_LINE_COUNT (count $menu_lines)

    # Draw below command line using terminal escape sequences
    printf '\e[s' >&2              # save cursor position
    printf '\n\e[J' >&2            # newline + clear to end of screen
    for line in $menu_lines
        printf '%s\n' "$line" >&2
    end
    printf '\e[u' >&2              # restore cursor position
end

function _clai_picker_clear_menu
    if test $_CLAI_PICKER_LINE_COUNT -gt 0
        printf '\e[s' >&2          # save cursor
        printf '\n\e[J' >&2        # newline + clear to end of screen
        printf '\e[u' >&2          # restore cursor
        set -g _CLAI_PICKER_LINE_COUNT 0
    end
end

function _clai_picker_apply
    set -l selected $_CLAI_PICKER_ITEMS[$_CLAI_PICKER_INDEX]
    if test -n "$selected"
        commandline -r -- $selected
        commandline -f end-of-line
    end
    _clai_picker_render
end

function _clai_picker_close
    _clai_picker_clear_menu
    set -g _CLAI_PICKER_ACTIVE false
    set -g _CLAI_PICKER_MODE ""
    set -g _CLAI_PICKER_ITEMS
    set -g _CLAI_PICKER_INDEX 1
end

function _clai_picker_cancel
    if test "$_CLAI_PICKER_ACTIVE" = "true"
        commandline -r -- $_CLAI_PICKER_ORIG_BUFFER
        commandline -f end-of-line
        _clai_picker_close
    end
end

function _clai_suggest_tab
    if test "$CLAI_OFF" = "1"; or _clai_session_off
        commandline -f complete
        return
    end
    if not _clai_config_enabled
        commandline -f complete
        return
    end
    # When history picker is active, Tab cycles scopes
    if test "$_CLAI_PICKER_ACTIVE" = "true" -a "$_CLAI_PICKER_MODE" = "history"
        switch $_CLAI_HISTORY_SCOPE
            case session
                set -g _CLAI_HISTORY_SCOPE global
            case '*'
                set -g _CLAI_HISTORY_SCOPE session
        end
        set -g _CLAI_PICKER_INDEX 1
        if _clai_picker_load_history
            _clai_picker_apply
        end
        return
    end
    if test "$_CLAI_PICKER_ACTIVE" != "true" -o "$_CLAI_PICKER_MODE" != "suggest"
        set -g _CLAI_PICKER_ORIG_BUFFER (commandline)
        set -g _CLAI_PICKER_MODE suggest
        set -g _CLAI_PICKER_INDEX 1
        set -g _CLAI_PICKER_ACTIVE true
        if not _clai_picker_load_suggest
            _clai_picker_close
            commandline -f complete
            return
        end
        _clai_picker_apply
        return
    end
    _clai_picker_next
end

function _clai_history_up
    if test "$CLAI_OFF" = "1"; or _clai_session_off
        commandline -f history-search-backward
        return
    end
    # Try TUI picker first (when inline picker is not already active)
    if test "$_CLAI_PICKER_ACTIVE" != "true"; and _clai_has_tui_picker
        _clai_tui_picker_open
        return
    end
    if not _clai_config_enabled
        commandline -f history-search-backward
        return
    end
    if test "$_CLAI_PICKER_ACTIVE" = "true" -a "$_CLAI_PICKER_MODE" = "suggest"
        _clai_picker_prev
        return
    end
    if test "$_CLAI_PICKER_ACTIVE" != "true" -o "$_CLAI_PICKER_MODE" != "history"
        set -g _CLAI_PICKER_ORIG_BUFFER (commandline)
        set -g _CLAI_PICKER_MODE history
        set -g _CLAI_PICKER_INDEX 1
        set -g _CLAI_PICKER_ACTIVE true
        if not _clai_picker_load_history
            _clai_picker_close
            commandline -f history-search-backward
            return
        end
        _clai_picker_apply
        return
    end
    _clai_picker_next
end

function _clai_picker_down
    if test "$_CLAI_PICKER_ACTIVE" = "true"
        if test "$_CLAI_PICKER_MODE" = "history"
            _clai_picker_prev
        else
            _clai_picker_next
        end
        return
    end
    commandline -f history-search-forward
end

function _clai_picker_next
    if test "$_CLAI_PICKER_ACTIVE" = "true"
        set -l item_count (count $_CLAI_PICKER_ITEMS)
        if test $item_count -eq 0
            return
        end
        if test $_CLAI_PICKER_INDEX -lt $item_count
            set -g _CLAI_PICKER_INDEX (math $_CLAI_PICKER_INDEX + 1)
        else
            set -g _CLAI_PICKER_INDEX 1
        end
        _clai_picker_apply
    end
end

function _clai_picker_prev
    if test "$_CLAI_PICKER_ACTIVE" = "true"
        set -l item_count (count $_CLAI_PICKER_ITEMS)
        if test $item_count -eq 0
            return
        end
        if test $_CLAI_PICKER_INDEX -gt 1
            set -g _CLAI_PICKER_INDEX (math $_CLAI_PICKER_INDEX - 1)
        else
            set -g _CLAI_PICKER_INDEX $item_count
        end
        _clai_picker_apply
    end
end

function _clai_history_scope_session
    set -g _CLAI_HISTORY_SCOPE session
    if test "$_CLAI_PICKER_ACTIVE" = "true" -a "$_CLAI_PICKER_MODE" = "history"
        set -g _CLAI_PICKER_INDEX 1
        _clai_picker_load_history; and _clai_picker_apply
    end
end

function _clai_history_scope_cwd
    set -g _CLAI_HISTORY_SCOPE cwd
    if test "$_CLAI_PICKER_ACTIVE" = "true" -a "$_CLAI_PICKER_MODE" = "history"
        set -g _CLAI_PICKER_INDEX 1
        _clai_picker_load_history; and _clai_picker_apply
    end
end

function _clai_history_scope_global
    set -g _CLAI_HISTORY_SCOPE global
    if test "$_CLAI_PICKER_ACTIVE" = "true" -a "$_CLAI_PICKER_MODE" = "history"
        set -g _CLAI_PICKER_INDEX 1
        _clai_picker_load_history; and _clai_picker_apply
    end
end

# Inline picker disabled — use shell defaults for Tab/arrows.
# The TUI picker (Alt+H) remains available.
bind \eh _clai_tui_picker_open            # Alt+H: always open TUI picker

# ============================================
# Feature 3: Voice Mode
# ============================================
# When activated, the next Enter press will run the input through voice conversion

set -g _AI_VOICE_MODE false

function _ai_enter_voice_mode
    set -g _AI_VOICE_MODE true
    commandline -f repaint
end

function _ai_voice_execute
    # If picker is open, accept the current selection (don't execute)
    if test "$_CLAI_PICKER_ACTIVE" = "true"
        _clai_picker_close
        return
    end

    set -l current_cmd (commandline)

    # Check for ? prefix (natural language input marker)
    if string match -q '\\?*' -- $current_cmd
        and test (string length -- $current_cmd) -gt 1
        # Remove the ? prefix and any leading space
        set -l nl_input (string replace -r '^\\?\\s*' '' -- $current_cmd)
        commandline -r ""

        echo "? $nl_input"
        set -l cmd (clai voice "$nl_input" 2>/dev/null)
        if test -n "$cmd"
            echo "→ $cmd"
            # Put command in buffer for user to review
            commandline -r $cmd
            commandline -f end-of-line
        end
        return
    end

    # Check for explicit voice mode
    if test "$_AI_VOICE_MODE" = "true"
        and test -n "$current_cmd"
        set -g _AI_VOICE_MODE false
        commandline -r ""

        echo "? $current_cmd"
        set -l cmd (clai voice "$current_cmd" 2>/dev/null)
        if test -n "$cmd"
            echo "→ $cmd"
            # Put command in buffer for user to review
            commandline -r $cmd
            commandline -f end-of-line
        end
        return
    end

    # Normal execute
    set -g _AI_VOICE_MODE false
    _clai_picker_clear_menu
    commandline -f execute
end

# Show voice mode indicator or suggestion in right prompt
function fish_right_prompt
    if test "$_AI_VOICE_MODE" = "true"
        set_color magenta
        echo -n "🎤 Voice mode"
        set_color normal
        return
    end

    set -l current (commandline)
    if test -n "$current"
        # Have input - get suggestion for prefix
        set -l suggestion (clai suggest "$current" 2>/dev/null)
        if test -n "$suggestion" -a "$suggestion" != "$current"
            set_color brblack
            echo -n "($current → $suggestion)"
            set_color normal
        end
    else if test -s $_AI_SUGGEST_FILE
        # No input - show cached AI suggestion
        set -l suggestion (cat $_AI_SUGGEST_FILE)
        if test -n "$suggestion"
            set_color brblack
            echo -n "($suggestion)"
            set_color normal
        end
    end
end

# Bind Ctrl+X Ctrl+V to enter voice mode
bind \cx\cv _ai_enter_voice_mode

# Bind Enter to voice-aware execute
bind \r _ai_voice_execute


# ============================================
# Output Capture (via wrapper function)
# ============================================

# Wrap command execution to capture output and auto-diagnose on failure
# Usage: run <command> - captures output, extracts suggestions, diagnoses errors
function run
    # Run command, capture output, pass through clai extract
    $argv 2>&1 | clai extract
    set -l exit_code $pipestatus[1]

    # Auto-diagnose if command failed
    if test $exit_code -ne 0
        echo ""
        set_color yellow
        echo "⚡ Analyzing error..."
        set_color normal
        clai diagnose "$argv" "$exit_code" 2>/dev/null
    end

    return $exit_code
end

# ============================================
# Session Tracking
# ============================================
# Session ID for this shell instance (generated by clai init)
set -gx CLAI_SESSION_ID "{{CLAI_SESSION_ID}}"

# ============================================
# Manual Commands
# ============================================

# Intercept history command to show session-specific history
# Falls back to shell history if no session history available
# Use `history --global` or `history -g` for shell-native history
function history --wraps=history
    if test (count $argv) -gt 0
        switch $argv[1]
            case '--global' '-g'
                # Pass through to builtin history (remove the --global flag)
                builtin history $argv[2..-1]
                return
            case '--help' '-h'
                echo "Usage: history [options] [query]"
                echo ""
                echo "Shows command history (session-specific if available, else shell history)."
                echo ""
                echo "Options:"
                echo "  -g, --global    Always use shell's native history"
                echo "  -n, --limit N   Maximum number of commands to show (default: 20)"
                echo "  --cwd PATH      Filter by working directory"
                echo ""
                echo "Examples:"
                echo "  history              # Show session or shell history"
                echo "  history git          # Filter to git commands"
                echo "  history --global     # Force shell's native history"
                return
        end
    end
    # Try clai session history first, fall back to shell history
    set -l output (clai history --session="$CLAI_SESSION_ID" $argv 2>/dev/null)
    if test -n "$output" -a "$output" != "*No command*"
        echo "$output"
    else
        # Fall back to shell's native history
        builtin history $argv
    end
end

# Manually diagnose last command
function ai-fix
    if test (count $argv) -gt 0
        set cmd $argv[1]
    else
        set cmd (builtin history --max=1)
    end
    clai diagnose "$cmd" "1"
end

# Ask Claude anything with terminal context
function ai
    if test (count $argv) -eq 0
        echo "Usage: ai \"your question\""
        return 1
    end

    set -l recent_cmds (builtin history --max=5 | string join ';')
    clai ask --context "$recent_cmds" $argv
end

# Convert voice/natural language to terminal command
function voice
    if test (count $argv) -eq 0
        echo "Usage: voice \"natural language description\""
        return 1
    end

    clai voice $argv
end

# ============================================
# Full Disable / Enable (clai off / clai on)
# ============================================

function _clai_disable
    set -gx CLAI_OFF 1

    # Restore default keybindings
    bind \t complete
    bind \e\[A history-search-backward
    bind \e\[B history-search-forward
    bind \r execute

    # Remove custom keybindings
    bind \e ''
    bind \e\r ''
    bind \eh ''
    bind \cx\cv ''
    bind \cx\cs ''
    bind \cx\cd ''
    bind \cx\cg ''

    # Restore native autosuggestions to their prior state
    if set -q _clai_prev_autosuggestion
        set -g fish_autosuggestion_enabled $_clai_prev_autosuggestion
        set -ge _clai_prev_autosuggestion
    else
        set -g fish_autosuggestion_enabled 1
    end

    # Remove custom fish_right_prompt and history wrapper
    functions -e fish_right_prompt
    functions -e history

    echo "clai disabled — native shell restored"
end

function _clai_enable
    set -ge CLAI_OFF
    set -l _saved_session $CLAI_SESSION_ID
    set -g _CLAI_REINIT 1
    command clai init fish | source
    set -ge _CLAI_REINIT
    # Preserve original session ID so history stays continuous
    set -gx CLAI_SESSION_ID $_saved_session
    echo "clai enabled"
end

# Wrapper function: intercepts off/on to run shell-native disable/enable
function clai --wraps=clai
    switch $argv[1]
        case off
            command clai $argv
            _clai_disable
        case on
            command clai $argv
            _clai_enable
        case '*'
            command clai $argv
    end
end

# ============================================
# Startup Message
# ============================================

if status is-interactive; and not set -q _CLAI_REINIT
    set -l short_id (string sub -l 8 -- $CLAI_SESSION_ID)
    set_color brblack
    echo "🤖 clai [$short_id] → suggest | Alt+↵ accept | ?\"describe task\""
    set_color normal
end
