# clai.fish - clai shell integration for Fish
# Generated by: clai init fish
#
# Features:
#   1. Auto-extract suggested commands from output
#   2. Error diagnosis with `run` wrapper (captures output for analysis)
#
# Configuration (set these BEFORE sourcing):
#   set -gx CLAI_AUTO_EXTRACT true

# ============================================
# Configuration
# ============================================

if not set -q CLAI_AUTO_EXTRACT
    set -gx CLAI_AUTO_EXTRACT true
end

if not set -q CLAI_CACHE
    set -gx CLAI_CACHE "$HOME/.cache/clai"
end

# Ensure cache directory exists
mkdir -p $CLAI_CACHE

# Files
set -g _AI_SUGGEST_FILE "$CLAI_CACHE/suggestion"
set -g _AI_LAST_OUTPUT "$CLAI_CACHE/last_output"

# ============================================
# Feature 1: Command Suggestion
# ============================================

# Accept suggestion with custom keybinding
function _ai_accept_suggestion
    if test -s $_AI_SUGGEST_FILE
        set -l suggestion (cat $_AI_SUGGEST_FILE)
        if test -n "$suggestion"
            commandline -r $suggestion
            commandline -f end-of-line
            # Clear the suggestion
            echo -n "" > $_AI_SUGGEST_FILE
            return
        end
    end
    # Default behavior: normal tab completion
    commandline -f complete
end

# Bind Alt+Enter to accept suggestion (Tab is used for completions in Fish)
bind \e\r _ai_accept_suggestion

# Clear suggestion with Escape
function _ai_clear_suggestion
    echo -n "" > $_AI_SUGGEST_FILE
    set -g _AI_VOICE_MODE false
    commandline -f repaint
end
bind \e _ai_clear_suggestion

# ============================================
# Feature 3: Voice Mode
# ============================================
# When activated, the next Enter press will run the input through voice conversion

set -g _AI_VOICE_MODE false

function _ai_enter_voice_mode
    set -g _AI_VOICE_MODE true
    commandline -f repaint
end

function _ai_voice_execute
    set -l current_cmd (commandline)

    # Check for ` prefix (voice input marker)
    if string match -q '`*' -- $current_cmd
        and test (string length -- $current_cmd) -gt 1
        # Remove the ` prefix and any leading space
        set -l voice_input (string replace -r '^`\\s*' '' -- $current_cmd)
        commandline -r ""

        echo "🎤 Converting: $voice_input"
        set -l cmd (clai voice "$voice_input" 2>/dev/null)
        if test -n "$cmd"
            echo "→ $cmd"
            # Put command in buffer for user to review
            commandline -r $cmd
            commandline -f end-of-line
        end
        return
    end

    # Check for explicit voice mode
    if test "$_AI_VOICE_MODE" = "true"
        and test -n "$current_cmd"
        set -g _AI_VOICE_MODE false
        commandline -r ""

        echo "🎤 Converting: $current_cmd"
        set -l cmd (clai voice "$current_cmd" 2>/dev/null)
        if test -n "$cmd"
            echo "→ $cmd"
            # Put command in buffer for user to review
            commandline -r $cmd
            commandline -f end-of-line
        end
        return
    end

    # Normal execute
    set -g _AI_VOICE_MODE false
    commandline -f execute
end

# Show voice mode indicator or suggestion in right prompt
function fish_right_prompt
    if test "$_AI_VOICE_MODE" = "true"
        set_color magenta
        echo -n "🎤 Voice mode"
        set_color normal
        return
    end

    set -l current (commandline)
    if test -n "$current"
        # Have input - get suggestion for prefix
        set -l suggestion (clai suggest "$current" 2>/dev/null)
        if test -n "$suggestion" -a "$suggestion" != "$current"
            set_color brblack
            echo -n "($current → $suggestion)"
            set_color normal
        end
    else if test -s $_AI_SUGGEST_FILE
        # No input - show cached AI suggestion
        set -l suggestion (cat $_AI_SUGGEST_FILE)
        if test -n "$suggestion"
            set_color brblack
            echo -n "($suggestion)"
            set_color normal
        end
    end
end

# Bind Ctrl+X Ctrl+V to enter voice mode
bind \cx\cv _ai_enter_voice_mode

# Bind Enter to voice-aware execute
bind \r _ai_voice_execute


# ============================================
# Output Capture (via wrapper function)
# ============================================

# Wrap command execution to capture output and auto-diagnose on failure
# Usage: run <command> - captures output, extracts suggestions, diagnoses errors
function run
    # Run command, capture output, pass through clai extract
    $argv 2>&1 | clai extract
    set -l exit_code $pipestatus[1]

    # Auto-diagnose if command failed
    if test $exit_code -ne 0
        echo ""
        set_color yellow
        echo "⚡ Analyzing error..."
        set_color normal
        clai diagnose "$argv" "$exit_code" 2>/dev/null
    end

    return $exit_code
end

# ============================================
# Manual Commands
# ============================================

# Manually diagnose last command
function ai-fix
    if test (count $argv) -gt 0
        set cmd $argv[1]
    else
        set cmd (history --max=1)
    end
    clai diagnose "$cmd" "1"
end

# Ask Claude anything with terminal context
function ai
    if test (count $argv) -eq 0
        echo "Usage: ai \"your question\""
        return 1
    end

    set -l recent_cmds (history --max=5 | string join ';')
    clai ask --context "$recent_cmds" $argv
end

# Convert voice/natural language to terminal command
function voice
    if test (count $argv) -eq 0
        echo "Usage: voice \"natural language description\""
        return 1
    end

    clai voice $argv
end

# ============================================
# Startup Message
# ============================================

if status is-interactive
    set_color brblack
    echo "🤖 clai loaded. Commands: ai-fix, ai, voice, run | ` prefix for voice mode"
    set_color normal
end
