# altool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/altool.1
complete -c altool -s u -l username
complete -c altool -s p -l app-password
complete -c altool -l api-key
complete -c altool -l api-issuer
complete -c altool -l api-key-subject
complete -c altool -l auth-string
complete -c altool -l output-format
complete -c altool -l show-progress
complete -c altool -l verbose
complete -c altool -l help
complete -c altool -l use-old-altool
complete -c altool -l upload-package
complete -c altool -s t -l platform
complete -c altool -l apple-id
complete -c altool -l bundle-version
complete -c altool -l bundle-short-version-string
complete -c altool -l provider-public-id
complete -c altool -l wait
complete -c altool -l validate-app
complete -c altool -l list-apps
complete -c altool -l filter-apple-id
complete -c altool -l filter-bundle-id
complete -c altool -l filter-name
complete -c altool -l filter-sku
complete -c altool -l filter-platform
complete -c altool -l list-providers
complete -c altool -l legacy
complete -c altool -l app-store-text -l upload
complete -c altool -l beta-app-store-text
complete -c altool -l upload-asset-pack
complete -c altool -l asset-pack-status
complete -c altool -l asset-pack-version-id
complete -c altool -l asset-pack-identifier
complete -c altool -l version
complete -c altool -l list-asset-packs
complete -c altool -l list-asset-pack-versions
complete -c altool -l store-password-in-keychain-item
complete -c altool -l keychain
complete -c altool -l sync
complete -c altool -l generate-jwt
complete -c altool -l build-status
complete -c altool -l delivery-id
complete -c altool -l app-settings

