# arkitd
# Autogenerated from man page /usr/share/man/man8/arkitd.8
complete -c arkitd -s a -d 'Description of -a flag'
complete -c arkitd -s b -d 'Description of -b flag \\" Ends the list FILES                \\" File used or …'

