# fsck_fskit
# Autogenerated from man page /usr/share/man/man8/fsck_fskit.8
complete -c fsck_fskit -l progress -d 'causes fsck_fskit to display a progres bar during the repair or verify operat…'
complete -c fsck_fskit -s t -d 'Use the FSKit Module named fstype to perform the repair or verify operation'

