# gbasename
# Autogenerated from man page /opt/homebrew/share/man/man1/gbasename.1
complete -c gbasename -l 'multiple\\X\'tty' -d 'support multiple arguments and treat each as a NAME'
complete -c gbasename -l suffix -d 'remove a trailing SUFFIX; implies -a'
complete -c gbasename -l 'zero\\X\'tty' -d 'end each output line with NUL, not newline'
complete -c gbasename -s '>'

