# gchmod
# Autogenerated from man page /opt/homebrew/share/man/man1/gchmod.1
complete -c gchmod -l 'changes\\X\'tty' -d 'like verbose but report only when a change is made'
complete -c gchmod -l silent -l 'quiet\\X\'tty' -d 'suppress most error messages'
complete -c gchmod -l 'verbose\\X\'tty' -d 'output a diagnostic for every file processed'
complete -c gchmod -l 'no-dereference\\X\'tty' -d 'affect each symbolic link, rather than the referent'
complete -c gchmod -l 'recursive\\X\'tty' -d 'change files and directories recursively '
complete -c gchmod -o 6000 -d 'or leading equals like =755 '

