# gcut
# Autogenerated from man page /opt/homebrew/share/man/man1/gcut.1
complete -c gcut -l bytes -d 'select only these bytes'
complete -c gcut -l characters -d 'select only these characters'
complete -c gcut -l delimiter -d 'use DELIM instead of TAB for field delimiter'
complete -c gcut -l fields -d 'select only these fields;  also print any line that contains no delimiter cha…'
complete -c gcut -l 'only-delimited\\X\'tty' -d 'do not print lines not containing delimiters'
complete -c gcut -l 'zero-terminated\\X\'tty' -d 'line delimiter is NUL, not newline'
complete -c gcut -s M -d 'from first to M\'th (included) byte, character or field AUTHOR Written by Davi…'

