# gdate
# Autogenerated from man page /opt/homebrew/share/man/man1/gdate.1
complete -c gdate -l date -d 'display time described by STRING, not \'now\''
complete -c gdate -l file -d 'like --date; once for each line of DATEFILE; if DATEFILE is -, read names fro…'
complete -c gdate -l iso-8601 -d 'output date/time in ISO 8601 format'
complete -c gdate -l 'rfc-email\\X\'tty' -d 'output date and time in RFC 5322 format'
complete -c gdate -l reference -d 'display the last modification time of FILE'
complete -c gdate -l set -d 'set time described by STRING'
complete -c gdate -l utc -l 'universal\\X\'tty' -d 'print or set Coordinated Universal Time (UTC)'

