# genv
# Autogenerated from man page /opt/homebrew/share/man/man1/genv.1
complete -c genv -l argv0 -d 'pass ARG as the zeroth argument of COMMAND'
complete -c genv -l 'ignore-environment\\X\'tty' -d 'start with an empty environment'
complete -c genv -l 'null\\X\'tty' -d 'end each output line with NUL, not newline'
complete -c genv -l unset -d 'remove variable from the environment'
complete -c genv -l chdir -d 'change working directory to DIR'
complete -c genv -l split-string -d 'process and split S into separate arguments; used to pass multiple arguments …'
complete -c genv -l 'debug\\X\'tty' -d 'print verbose information for each processing step'
complete -c genv -s S -d 'option allows specifying multiple arguments in a script'

