# gh-agent-task-create
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-agent-task-create.1
complete -c gh-agent-task-create -s b -l base -d 'Base branch for the pull request (use default branch if not provided)'
complete -c gh-agent-task-create -s a -l custom-agent -d 'Use a custom agent for the task.  e. g. , use \'my-agent\' for the \'my-agent'
complete -c gh-agent-task-create -l follow -d 'Follow agent session logs'
complete -c gh-agent-task-create -s F -l from-file -d 'Read task description from file (use "-" to read from standard input)'
complete -c gh-agent-task-create -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

