# gh-auth-status
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-auth-status.1
complete -c gh-auth-status -s a -l active -d 'Display the active account only'
complete -c gh-auth-status -s h -l hostname -d 'Check only a specific hostname\'s auth status'
complete -c gh-auth-status -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-auth-status -l json -d 'Output JSON with the specified fields'
complete -c gh-auth-status -s t -l show-token -d 'Display the auth token'
complete -c gh-auth-status -l template -d 'Format JSON output using a Go template; see "gh help formatting" JSON FIELDS …'

