# gh-agent-task-view
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-agent-task-view.1
complete -c gh-agent-task-view -l follow -d 'Follow agent session logs'
complete -c gh-agent-task-view -l log -d 'Show agent session logs'
complete -c gh-agent-task-view -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format'
complete -c gh-agent-task-view -s w -l web -d 'Open agent task in the browser EXIT CODES 0: Successful execution 1: Error 2:…'

