# gh-agent-task-list
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-agent-task-list.1
complete -c gh-agent-task-list -s L -l limit -d 'Maximum number of agent tasks to fetch'
complete -c gh-agent-task-list -s w -l web -d 'Open agent tasks in the browser EXIT CODES 0: Successful execution 1: Error 2…'

