# gh-cache-delete
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-cache-delete.1
complete -c gh-cache-delete -s a -l all -d 'Delete all caches, can be used with --ref to delete all caches for a specific…'
complete -c gh-cache-delete -s r -l ref -d 'Delete by cache key and ref, formatted as refs/heads/ or refs/pull//merge'
complete -c gh-cache-delete -l succeed-on-no-caches -d 'Return exit code 0 if no caches found'
complete -c gh-cache-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

