# gh-copilot
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-copilot.1
complete -c gh-copilot -l remove -d 'Remove the downloaded Copilot CLI EXIT CODES 0: Successful execution 1: Error…'

