# gh-codespace-create
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-codespace-create.1
complete -c gh-codespace-create -s b -l branch -d 'Repository branch'
complete -c gh-codespace-create -l default-permissions -d 'Do not prompt to accept additional permissions requested by the codespace'
complete -c gh-codespace-create -l devcontainer-path -d 'Path to the devcontainer. json file to use when creating codespace'
complete -c gh-codespace-create -s d -l display-name -d 'Display name for the codespace (48 characters or less)'
complete -c gh-codespace-create -l idle-timeout -d 'Allowed inactivity before codespace is stopped, e. g.  "10m", "1h"'
complete -c gh-codespace-create -s l -l location -d 'Location: {EastUs|SouthEastAsia|WestEurope|WestUs2} (determined automatically…'
complete -c gh-codespace-create -s m -l machine -d 'Hardware specifications for the VM'
complete -c gh-codespace-create -s R -l repo -d 'Repository name with owner: user/repo'
complete -c gh-codespace-create -l retention-period -d 'Allowed time after shutting down before the codespace is automatically delete…'
complete -c gh-codespace-create -s s -l status -d 'Show status of post-create command and dotfiles'
complete -c gh-codespace-create -s w -l web -d 'Create codespace from browser, cannot be used with --display-name, --idle-tim…'

