# gh-extension-install
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-extension-install.1
complete -c gh-extension-install -l force -d 'Force upgrade extension, or ignore if latest already installed'
complete -c gh-extension-install -l pin -d 'Pin extension to a release tag or commit ref EXIT CODES 0: Successful executi…'

