# gh-gist-delete
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-gist-delete.1
complete -c gh-gist-delete -l yes -d 'Confirm deletion without prompting EXIT CODES 0: Successful execution 1: Erro…'

