# gh-issue-comment
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-issue-comment.1
complete -c gh-issue-comment -s b -l body -d 'The comment body text'
complete -c gh-issue-comment -s F -l body-file -d 'Read body text from file (use "-" to read from standard input)'
complete -c gh-issue-comment -l create-if-none -d 'Create a new comment if no comments are found'
complete -c gh-issue-comment -l delete-last -d 'Delete the last comment of the current user'
complete -c gh-issue-comment -l edit-last -d 'Edit the last comment of the current user'
complete -c gh-issue-comment -s e -l editor -d 'Skip prompts and open the text editor to write the body in'
complete -c gh-issue-comment -s w -l web -d 'Open the web browser to write the comment'
complete -c gh-issue-comment -l yes -d 'Skip the delete confirmation prompt when --delete-last is provided OPTIONS IN…'
complete -c gh-issue-comment -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

