# gh-pr-revert
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-pr-revert.1
complete -c gh-pr-revert -s b -l body -d 'Body for the revert pull request'
complete -c gh-pr-revert -s F -l body-file -d 'Read body text from file (use "-" to read from standard input)'
complete -c gh-pr-revert -s d -l draft -d 'Mark revert pull request as a draft'
complete -c gh-pr-revert -s t -l title -d 'Title for the revert pull request OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-revert -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

