# gh-repo-autolink-create
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-repo-autolink-create.1
complete -c gh-repo-autolink-create -s n -l numeric -d 'Mark autolink as numeric OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-repo-autolink-create -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format ALIASES gh repo …'

