# gh-repo-autolink-delete
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-repo-autolink-delete.1
complete -c gh-repo-autolink-delete -l yes -d 'Confirm deletion without prompting OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-repo-autolink-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

