# gh-release-verify
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-release-verify.1
complete -c gh-release-verify -l format -d 'Output format: {json}'
complete -c gh-release-verify -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-release-verify -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" OPTIONS INHE…'
complete -c gh-release-verify -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

