# gnumfmt
# Autogenerated from man page /opt/homebrew/share/man/man1/gnumfmt.1
complete -c gnumfmt -l delimiter -d 'use X instead of whitespace for field delimiter'
complete -c gnumfmt -l 'zero-terminated\\X\'tty' -d 'line delimiter is NUL, not newline'
complete -c gnumfmt -s M -d 'from first to M\'th field (inclusive)'
complete -c gnumfmt -s '>' -d '$ numfmt --to=iec 2048'

