# grm
# Autogenerated from man page /opt/homebrew/share/man/man1/grm.1
complete -c grm -l 'force\\X\'tty' -d 'ignore nonexistent files and arguments, never prompt'
complete -c grm -s R -l 'recursive\\X\'tty' -d 'remove directories and their contents recursively'
complete -c grm -l 'dir\\X\'tty' -d 'remove empty directories'
complete -c grm -l 'verbose\\X\'tty' -d 'explain what is being done'
complete -c grm -s i -l interactive -d 'rm prompts the user for whether to remove the file'

