# gsplit
# Autogenerated from man page /opt/homebrew/share/man/man1/gsplit.1
complete -c gsplit -l suffix-length -d 'generate suffixes of length N (default 2)'
complete -c gsplit -l bytes -d 'put SIZE bytes per output file'
complete -c gsplit -l line-bytes -d 'put at most SIZE bytes of records per output file'
complete -c gsplit -l 'elide-empty-files\\X\'tty' -d 'do not generate empty output files with \'-n\''
complete -c gsplit -l lines -d 'put NUMBER lines/records per output file'
complete -c gsplit -l number -d 'generate CHUNKS output files; see explanation below'
complete -c gsplit -l separator -d 'use SEP instead of newline as the record separator; \'0\' (zero) specifies the …'
complete -c gsplit -l 'unbuffered\\X\'tty' -d 'immediately copy input to output with \'-n r/. \''
complete -c gsplit -s n -o nr -d 'if the input size cannot easily be determined'

