# gstat
# Autogenerated from man page /opt/homebrew/share/man/man1/gstat.1
complete -c gstat -l 'dereference\\X\'tty' -d 'follow links'
complete -c gstat -l 'file-system\\X\'tty' -d 'display file system status instead of file status'
complete -c gstat -l format -d 'use the specified FORMAT instead of the default; output a newline after each …'
complete -c gstat -l 'terse\\X\'tty' -d 'print the information in terse form'
complete -c gstat -l terse -d '%n %s %b %f %u %g %D %i %h %t %T %X %Y %Z %W %o'
complete -c gstat -l file-system -d '%n %i %l %t %s %S %b %f %a %c %d'

