# gstdbuf
# Autogenerated from man page /opt/homebrew/share/man/man1/gstdbuf.1
complete -c gstdbuf -l input -d 'adjust standard input stream buffering'
complete -c gstdbuf -l output -d 'adjust standard output stream buffering'
complete -c gstdbuf -l error -d 'adjust standard error stream buffering'

