# gstty
# Autogenerated from man page /opt/homebrew/share/man/man1/gstty.1
complete -c gstty -l 'all\\X\'tty' -d 'print all current settings in human-readable form'
complete -c gstty -l 'save\\X\'tty' -d 'print all current settings in a stty-readable form'
complete -c gstty -l file -d 'open and use DEVICE instead of standard input'
complete -c gstty -o tabs -d 'same as tab3'
complete -c gstty -o crtkill -d 'kill all line by obeying the echoctl and echok settings'
complete -c gstty -o cbreak -d 'same as icanon'
complete -c gstty -o cooked -d 'same as raw'
complete -c gstty -o evenp -d 'same as -parenb cs8'
complete -c gstty -o litout -d 'same as parenb istrip opost cs7'
complete -c gstty -o nl -d 'same as icrnl -inlcr -igncr onlcr -ocrnl -onlret'
complete -c gstty -o oddp -d 'same as -parenb cs8'
complete -c gstty -o pass8 -d 'same as parenb istrip cs7'
complete -c gstty -o raw -d 'same as cooked'
complete -c gstty -o inlcr -o igncr -o icrnl -o ixon -o ixoff -o icanon -o opost
complete -c gstty -o isig -o ixany -o imaxbel
complete -c gstty -o iutf8 -o ocrnl -d 'opost -ofill onlcr -onocr -onlret nl0 cr0 tab0 bs0 vt0 ff0 isig -tostop -ofde…'

