# gtimeout
# Autogenerated from man page /opt/homebrew/share/man/man1/gtimeout.1
complete -c gtimeout -l 'foreground\\X\'tty' -d 'when not running timeout directly from a shell prompt, allow COMMAND to read …'
complete -c gtimeout -l kill-after -d 'also send a KILL signal if COMMAND is still running this long after the initi…'
complete -c gtimeout -l 'preserve-status\\X\'tty' -d 'exit with the same status as COMMAND, even when the command times out'
complete -c gtimeout -l signal -d 'specify the signal to be sent on timeout; SIGNAL may be a name like \'HUP\' or …'
complete -c gtimeout -l 'verbose\\X\'tty' -d 'diagnose to standard error any signal sent upon timeout'

