# gtr
# Autogenerated from man page /opt/homebrew/share/man/man1/gtr.1
complete -c gtr -s C -l 'complement\\X\'tty' -d 'use the complement of ARRAY1'
complete -c gtr -l 'delete\\X\'tty' -d 'delete characters in ARRAY1, do not translate'
complete -c gtr -l 'squeeze-repeats\\X\'tty' -d 'replace each sequence of a repeated character that is listed in the last spec…'
complete -c gtr -l 'truncate-set1\\X\'tty' -d 'first truncate ARRAY1 to length of ARRAY2'
complete -c gtr -s t -d 'ARRAY1 by repeating its last character as necessary'

