# hugo-list-expired
# Autogenerated from man page /opt/homebrew/share/man/man1/hugo-list-expired.1
complete -c hugo-list-expired -s h -l help -d '	help for expired OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c hugo-list-expired -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-list-expired -l config -d '	config file (default is hugo. yaml|json|toml)'
complete -c hugo-list-expired -l configDir -d '	config dir'
complete -c hugo-list-expired -s d -l destination -d '	filesystem path to write files to'
complete -c hugo-list-expired -s e -l environment -d '	build environment'
complete -c hugo-list-expired -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-list-expired -l logLevel -d '	log level (debug|info|warn|error)'
complete -c hugo-list-expired -l noBuildLock -d '	don\'t create . hugo_build. lock file'
complete -c hugo-list-expired -l quiet -d '	build in quiet mode'
complete -c hugo-list-expired -s M -l renderToMemory -d '	render to memory (mostly useful when running the server)'
complete -c hugo-list-expired -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-list-expired -l themesDir -d '	filesystem path to themes directory SEE ALSO hugo-list(1)'

