# hugo-list-drafts
# Autogenerated from man page /opt/homebrew/share/man/man1/hugo-list-drafts.1
complete -c hugo-list-drafts -s h -l help -d '	help for drafts OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c hugo-list-drafts -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-list-drafts -l config -d '	config file (default is hugo. yaml|json|toml)'
complete -c hugo-list-drafts -l configDir -d '	config dir'
complete -c hugo-list-drafts -s d -l destination -d '	filesystem path to write files to'
complete -c hugo-list-drafts -s e -l environment -d '	build environment'
complete -c hugo-list-drafts -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-list-drafts -l logLevel -d '	log level (debug|info|warn|error)'
complete -c hugo-list-drafts -l noBuildLock -d '	don\'t create . hugo_build. lock file'
complete -c hugo-list-drafts -l quiet -d '	build in quiet mode'
complete -c hugo-list-drafts -s M -l renderToMemory -d '	render to memory (mostly useful when running the server)'
complete -c hugo-list-drafts -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-list-drafts -l themesDir -d '	filesystem path to themes directory SEE ALSO hugo-list(1)'

