# hugo-import-jekyll
# Autogenerated from man page /opt/homebrew/share/man/man1/hugo-import-jekyll.1
complete -c hugo-import-jekyll -l force -d '	allow import into non-empty target directory'
complete -c hugo-import-jekyll -s h -l help -d '	help for jekyll OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c hugo-import-jekyll -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-import-jekyll -l config -d '	config file (default is hugo. yaml|json|toml)'
complete -c hugo-import-jekyll -l configDir -d '	config dir'
complete -c hugo-import-jekyll -s d -l destination -d '	filesystem path to write files to'
complete -c hugo-import-jekyll -s e -l environment -d '	build environment'
complete -c hugo-import-jekyll -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-import-jekyll -l logLevel -d '	log level (debug|info|warn|error)'
complete -c hugo-import-jekyll -l noBuildLock -d '	don\'t create . hugo_build. lock file'
complete -c hugo-import-jekyll -l quiet -d '	build in quiet mode'
complete -c hugo-import-jekyll -s M -l renderToMemory -d '	render to memory (mostly useful when running the server)'
complete -c hugo-import-jekyll -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-import-jekyll -l themesDir -d '	filesystem path to themes directory SEE ALSO hugo-import(1)'

