# hugo-gen-man
# Autogenerated from man page /opt/homebrew/share/man/man1/hugo-gen-man.1
complete -c hugo-gen-man -l dir -d '	the directory to write the man pages'
complete -c hugo-gen-man -s h -l help -d '	help for man OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c hugo-gen-man -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-gen-man -l config -d '	config file (default is hugo. yaml|json|toml)'
complete -c hugo-gen-man -l configDir -d '	config dir'
complete -c hugo-gen-man -s d -l destination -d '	filesystem path to write files to'
complete -c hugo-gen-man -s e -l environment -d '	build environment'
complete -c hugo-gen-man -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-gen-man -l logLevel -d '	log level (debug|info|warn|error)'
complete -c hugo-gen-man -l noBuildLock -d '	don\'t create . hugo_build. lock file'
complete -c hugo-gen-man -l quiet -d '	build in quiet mode'
complete -c hugo-gen-man -s M -l renderToMemory -d '	render to memory (mostly useful when running the server)'
complete -c hugo-gen-man -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-gen-man -l themesDir -d '	filesystem path to themes directory SEE ALSO hugo-gen(1)'

