# hugo-new-site
# Autogenerated from man page /opt/homebrew/share/man/man1/hugo-new-site.1
complete -c hugo-new-site -s f -l force -d '	init inside non-empty directory'
complete -c hugo-new-site -l format -d '	preferred file format (toml, yaml or json)'
complete -c hugo-new-site -s h -l help -d '	help for site OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c hugo-new-site -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-new-site -l config -d '	config file (default is hugo. yaml|json|toml)'
complete -c hugo-new-site -l configDir -d '	config dir'
complete -c hugo-new-site -s d -l destination -d '	filesystem path to write files to'
complete -c hugo-new-site -s e -l environment -d '	build environment'
complete -c hugo-new-site -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-new-site -l logLevel -d '	log level (debug|info|warn|error)'
complete -c hugo-new-site -l noBuildLock -d '	don\'t create . hugo_build. lock file'
complete -c hugo-new-site -l quiet -d '	build in quiet mode'
complete -c hugo-new-site -s M -l renderToMemory -d '	render to memory (mostly useful when running the server)'
complete -c hugo-new-site -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-new-site -l themesDir -d '	filesystem path to themes directory SEE ALSO hugo-new(1)'

