# hugo-server-trust
# Autogenerated from man page /opt/homebrew/share/man/man1/hugo-server-trust.1
complete -c hugo-server-trust -s h -l help -d '	help for trust'
complete -c hugo-server-trust -l uninstall -d '	Uninstall the local CA (but do not delete it)'
complete -c hugo-server-trust -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-server-trust -l config -d '	config file (default is hugo. yaml|json|toml)'
complete -c hugo-server-trust -l configDir -d '	config dir'
complete -c hugo-server-trust -s d -l destination -d '	filesystem path to write files to'
complete -c hugo-server-trust -s e -l environment -d '	build environment'
complete -c hugo-server-trust -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-server-trust -l logLevel -d '	log level (debug|info|warn|error)'
complete -c hugo-server-trust -l noBuildLock -d '	don\'t create . hugo_build. lock file'
complete -c hugo-server-trust -l quiet -d '	build in quiet mode'
complete -c hugo-server-trust -s M -l renderToMemory -d '	render to memory (mostly useful when running the server)'
complete -c hugo-server-trust -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-server-trust -l themesDir -d '	filesystem path to themes directory SEE ALSO hugo-server(1)'

