# hugo-completion-fish
# Autogenerated from man page /opt/homebrew/share/man/man1/hugo-completion-fish.1
complete -c hugo-completion-fish -s h -l help -d '	help for fish'
complete -c hugo-completion-fish -l no-descriptions -d '	disable completion descriptions OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c hugo-completion-fish -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-completion-fish -l config -d '	config file (default is hugo. yaml|json|toml)'
complete -c hugo-completion-fish -l configDir -d '	config dir'
complete -c hugo-completion-fish -s d -l destination -d '	filesystem path to write files to'
complete -c hugo-completion-fish -s e -l environment -d '	build environment'
complete -c hugo-completion-fish -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-completion-fish -l logLevel -d '	log level (debug|info|warn|error)'
complete -c hugo-completion-fish -l noBuildLock -d '	don\'t create . hugo_build. lock file'
complete -c hugo-completion-fish -l quiet -d '	build in quiet mode'
complete -c hugo-completion-fish -s M -l renderToMemory -d '	render to memory (mostly useful when running the server)'
complete -c hugo-completion-fish -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-completion-fish -l themesDir -d '	filesystem path to themes directory SEE ALSO hugo-completion(1)'

