# hugo-convert
# Autogenerated from man page /opt/homebrew/share/man/man1/hugo-convert.1
complete -c hugo-convert -s h -l help -d '	help for convert'
complete -c hugo-convert -s o -l output -d '	filesystem path to write files to'
complete -c hugo-convert -l unsafe -d '	enable less safe operations, please backup first OPTIONS INHERITED FROM PARE…'
complete -c hugo-convert -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-convert -l config -d '	config file (default is hugo. yaml|json|toml)'
complete -c hugo-convert -l configDir -d '	config dir'
complete -c hugo-convert -s d -l destination -d '	filesystem path to write files to'
complete -c hugo-convert -s e -l environment -d '	build environment'
complete -c hugo-convert -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-convert -l logLevel -d '	log level (debug|info|warn|error)'
complete -c hugo-convert -l noBuildLock -d '	don\'t create . hugo_build. lock file'
complete -c hugo-convert -l quiet -d '	build in quiet mode'
complete -c hugo-convert -s M -l renderToMemory -d '	render to memory (mostly useful when running the server)'
complete -c hugo-convert -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-convert -l themesDir -d '	filesystem path to themes directory SEE ALSO hugo(1), hugo-convert-toJSON(1)…'

