# hugo-convert-toTOML
# Autogenerated from man page /opt/homebrew/share/man/man1/hugo-convert-toTOML.1
complete -c hugo-convert-toTOML -s h -l help -d '	help for toTOML OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c hugo-convert-toTOML -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-convert-toTOML -l config -d '	config file (default is hugo. yaml|json|toml)'
complete -c hugo-convert-toTOML -l configDir -d '	config dir'
complete -c hugo-convert-toTOML -s d -l destination -d '	filesystem path to write files to'
complete -c hugo-convert-toTOML -s e -l environment -d '	build environment'
complete -c hugo-convert-toTOML -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-convert-toTOML -l logLevel -d '	log level (debug|info|warn|error)'
complete -c hugo-convert-toTOML -l noBuildLock -d '	don\'t create . hugo_build. lock file'
complete -c hugo-convert-toTOML -s o -l output -d '	filesystem path to write files to'
complete -c hugo-convert-toTOML -l quiet -d '	build in quiet mode'
complete -c hugo-convert-toTOML -s M -l renderToMemory -d '	render to memory (mostly useful when running the server)'
complete -c hugo-convert-toTOML -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-convert-toTOML -l themesDir -d '	filesystem path to themes directory'
complete -c hugo-convert-toTOML -l unsafe -d '	enable less safe operations, please backup first SEE ALSO hugo-convert(1)'

