# kubeadm-init-phase-certs-etcd-healthcheck-client
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-certs-etcd-healthcheck-client.1
complete -c kubeadm-init-phase-certs-etcd-healthcheck-client -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-certs-etcd-healthcheck-client -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-certs-etcd-healthcheck-client -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-certs-etcd-healthcheck-client -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-init-phase-certs-etcd-healthcheck-client -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-certs-etcd-healthcheck-client -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

