# kubeadm-join-phase-kubelet-wait-bootstrap
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-join-phase-kubelet-wait-bootstrap.1
complete -c kubeadm-join-phase-kubelet-wait-bootstrap -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-join-phase-kubelet-wait-bootstrap -l cri-socket -d '	Path to the CRI socket to connect'
complete -c kubeadm-join-phase-kubelet-wait-bootstrap -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-join-phase-kubelet-wait-bootstrap -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-join-phase-kubelet-wait-bootstrap -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

