# kubeadm-init-phase-control-plane-apiserver
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-control-plane-apiserver.1
complete -c kubeadm-init-phase-control-plane-apiserver -l apiserver-advertise-address -d '	The IP address the API Server will advertise it\'s listening on'
complete -c kubeadm-init-phase-control-plane-apiserver -l apiserver-bind-port -d '	Port for the API Server to bind to'
complete -c kubeadm-init-phase-control-plane-apiserver -l apiserver-extra-args -d '	A set of extra flags to pass to the API Server or override default ones in f…'
complete -c kubeadm-init-phase-control-plane-apiserver -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-control-plane-apiserver -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-control-plane-apiserver -l control-plane-endpoint -d '	Specify a stable IP address or DNS name for the control plane'
complete -c kubeadm-init-phase-control-plane-apiserver -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-control-plane-apiserver -l feature-gates -d '	A set of key=value pairs that describe feature gates for various features'
complete -c kubeadm-init-phase-control-plane-apiserver -l image-repository -d '	Choose a container registry to pull control plane images from'
complete -c kubeadm-init-phase-control-plane-apiserver -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-init-phase-control-plane-apiserver -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-init-phase-control-plane-apiserver -l service-cidr -d '	Use alternative range of IP address for service VIPs'
complete -c kubeadm-init-phase-control-plane-apiserver -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-control-plane-apiserver -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

