# kubeadm-token-create
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-token-create.1
complete -c kubeadm-token-create -l certificate-key -d '	When used together with \'--print-join-command\', print the full \'kubeadm join…'
complete -c kubeadm-token-create -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-token-create -l description -d '	A human friendly description of how this token is used'
complete -c kubeadm-token-create -l groups -d '	Extra groups that this token will authenticate as when used for authenticati…'
complete -c kubeadm-token-create -l print-join-command -d '	Instead of printing only the token, print the full \'kubeadm join\' flag neede…'
complete -c kubeadm-token-create -l ttl -d '	The duration before the token is automatically deleted (e. g.  1s, 2m, 3h)'
complete -c kubeadm-token-create -l usages -d '	Describes the ways in which this token can be used'
complete -c kubeadm-token-create -l dry-run -d '	Whether to enable dry-run mode or not'
complete -c kubeadm-token-create -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-token-create -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-token-create -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

