# kubeadm-upgrade
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade.1
complete -c kubeadm-upgrade -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

