# kubeadm-init-phase-certs-apiserver
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-certs-apiserver.1
complete -c kubeadm-init-phase-certs-apiserver -l apiserver-advertise-address -d '	The IP address the API Server will advertise it\'s listening on'
complete -c kubeadm-init-phase-certs-apiserver -l apiserver-cert-extra-sans -d '	Optional extra Subject Alternative Names (SANs) to use for the API Server se…'
complete -c kubeadm-init-phase-certs-apiserver -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-certs-apiserver -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-certs-apiserver -l control-plane-endpoint -d '	Specify a stable IP address or DNS name for the control plane'
complete -c kubeadm-init-phase-certs-apiserver -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-certs-apiserver -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-init-phase-certs-apiserver -l service-cidr -d '	Use alternative range of IP address for service VIPs'
complete -c kubeadm-init-phase-certs-apiserver -l service-dns-domain -d '	Use alternative domain for services, e. g.  "myorg. internal"'
complete -c kubeadm-init-phase-certs-apiserver -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-certs-apiserver -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

