# kubeadm-init-phase-addon-all
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-addon-all.1
complete -c kubeadm-init-phase-addon-all -l apiserver-advertise-address -d '	The IP address the API Server will advertise it\'s listening on'
complete -c kubeadm-init-phase-addon-all -l apiserver-bind-port -d '	Port for the API Server to bind to'
complete -c kubeadm-init-phase-addon-all -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-addon-all -l control-plane-endpoint -d '	Specify a stable IP address or DNS name for the control plane'
complete -c kubeadm-init-phase-addon-all -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-addon-all -l feature-gates -d '	A set of key=value pairs that describe feature gates for various features'
complete -c kubeadm-init-phase-addon-all -l image-repository -d '	Choose a container registry to pull control plane images from'
complete -c kubeadm-init-phase-addon-all -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-init-phase-addon-all -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-init-phase-addon-all -l pod-network-cidr -d '	Specify range of IP addresses for the pod network'
complete -c kubeadm-init-phase-addon-all -l service-cidr -d '	Use alternative range of IP address for service VIPs'
complete -c kubeadm-init-phase-addon-all -l service-dns-domain -d '	Use alternative domain for services, e. g.  "myorg. internal"'
complete -c kubeadm-init-phase-addon-all -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-addon-all -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

