# kubeadm-completion
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-completion.1
complete -c kubeadm-completion -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-completion -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

