# kubeadm-init-phase-bootstrap-token
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-bootstrap-token.1
complete -c kubeadm-init-phase-bootstrap-token -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-bootstrap-token -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-bootstrap-token -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-init-phase-bootstrap-token -l skip-token-print -d '	Skip printing of the default bootstrap token generated by \'kubeadm init\''
complete -c kubeadm-init-phase-bootstrap-token -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-bootstrap-token -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

