# kubeadm-reset-phase-cleanup-node
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-reset-phase-cleanup-node.1
complete -c kubeadm-reset-phase-cleanup-node -l cert-dir -d '	The path to the directory where the certificates are stored'
complete -c kubeadm-reset-phase-cleanup-node -l cleanup-tmp-dir -d '	Cleanup the "/etc/kubernetes/tmp" directory'
complete -c kubeadm-reset-phase-cleanup-node -l cri-socket -d '	Path to the CRI socket to connect'
complete -c kubeadm-reset-phase-cleanup-node -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-reset-phase-cleanup-node -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-reset-phase-cleanup-node -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

