# kubeadm-upgrade-node-phase-addon-all
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade-node-phase-addon-all.1
complete -c kubeadm-upgrade-node-phase-addon-all -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-upgrade-node-phase-addon-all -l dry-run -d '	Do not change any state, just output the actions that would be performed'
complete -c kubeadm-upgrade-node-phase-addon-all -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-node-phase-addon-all -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-upgrade-node-phase-addon-all -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-node-phase-addon-all -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

