# kubeadm-reset-phase-remove-etcd-member
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-reset-phase-remove-etcd-member.1
complete -c kubeadm-reset-phase-remove-etcd-member -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-reset-phase-remove-etcd-member -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-reset-phase-remove-etcd-member -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-reset-phase-remove-etcd-member -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

