# kubeadm-upgrade-plan
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade-plan.1
complete -c kubeadm-upgrade-plan -l allow-experimental-upgrades -d '	Show unstable versions of Kubernetes as an upgrade alternative and allow upg…'
complete -c kubeadm-upgrade-plan -l allow-missing-template-keys -d '	If true, ignore any errors in templates when a field or map key is missing i…'
complete -c kubeadm-upgrade-plan -l allow-release-candidate-upgrades -d '	Show release candidate versions of Kubernetes as an upgrade alternative and …'
complete -c kubeadm-upgrade-plan -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-upgrade-plan -l etcd-upgrade -d '	Perform the upgrade of etcd'
complete -c kubeadm-upgrade-plan -l ignore-preflight-errors -d '	A list of checks whose errors will be shown as warnings'
complete -c kubeadm-upgrade-plan -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-plan -s o -l output -d '	Output format'
complete -c kubeadm-upgrade-plan -l print-config -d '	Specifies whether the configuration file that will be used in the upgrade sh…'
complete -c kubeadm-upgrade-plan -l show-managed-fields -d '	If true, keep the managedFields when printing objects in JSON or YAML format'
complete -c kubeadm-upgrade-plan -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-plan -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

