# kubeadm-upgrade-apply
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade-apply.1
complete -c kubeadm-upgrade-apply -l allow-experimental-upgrades -d '	Show unstable versions of Kubernetes as an upgrade alternative and allow upg…'
complete -c kubeadm-upgrade-apply -l allow-release-candidate-upgrades -d '	Show release candidate versions of Kubernetes as an upgrade alternative and …'
complete -c kubeadm-upgrade-apply -l certificate-renewal -d '	Perform the renewal of certificates used by component changed during upgrades'
complete -c kubeadm-upgrade-apply -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-upgrade-apply -l dry-run -d '	Do not change any state, just output what actions would be performed'
complete -c kubeadm-upgrade-apply -l etcd-upgrade -d '	Perform the upgrade of etcd'
complete -c kubeadm-upgrade-apply -s f -l force -d '	Force upgrading although some requirements might not be met'
complete -c kubeadm-upgrade-apply -l ignore-preflight-errors -d '	A list of checks whose errors will be shown as warnings'
complete -c kubeadm-upgrade-apply -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-apply -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-upgrade-apply -l print-config -d '	Specifies whether the configuration file that will be used in the upgrade sh…'
complete -c kubeadm-upgrade-apply -l skip-phases -d '	List of phases to be skipped'
complete -c kubeadm-upgrade-apply -s y -l yes -d '	Perform the upgrade and do not prompt for confirmation (non-interactive mode)'
complete -c kubeadm-upgrade-apply -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-apply -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

