# kubeadm-init-phase-etcd-local
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-etcd-local.1
complete -c kubeadm-init-phase-etcd-local -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-etcd-local -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-etcd-local -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-etcd-local -l image-repository -d '	Choose a container registry to pull control plane images from'
complete -c kubeadm-init-phase-etcd-local -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-init-phase-etcd-local -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-etcd-local -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

