# kubeadm-config-images-pull
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-config-images-pull.1
complete -c kubeadm-config-images-pull -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-config-images-pull -l cri-socket -d '	Path to the CRI socket to connect'
complete -c kubeadm-config-images-pull -l feature-gates -d '	A set of key=value pairs that describe feature gates for various features'
complete -c kubeadm-config-images-pull -l image-repository -d '	Choose a container registry to pull control plane images from'
complete -c kubeadm-config-images-pull -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-config-images-pull -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-config-images-pull -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-config-images-pull -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

