# kubeadm-reset
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-reset.1
complete -c kubeadm-reset -l cert-dir -d '	The path to the directory where the certificates are stored'
complete -c kubeadm-reset -l cleanup-tmp-dir -d '	Cleanup the "/etc/kubernetes/tmp" directory'
complete -c kubeadm-reset -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-reset -l cri-socket -d '	Path to the CRI socket to connect'
complete -c kubeadm-reset -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-reset -s f -l force -d '	Reset the node without prompting for confirmation'
complete -c kubeadm-reset -l ignore-preflight-errors -d '	A list of checks whose errors will be shown as warnings'
complete -c kubeadm-reset -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-reset -l skip-phases -d '	List of phases to be skipped OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c kubeadm-reset -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-reset -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

