# kubeadm-init-phase-upload-certs
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-upload-certs.1
complete -c kubeadm-init-phase-upload-certs -l certificate-key -d '	Key used to encrypt the control-plane certificates in the kubeadm-certs Secr…'
complete -c kubeadm-init-phase-upload-certs -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-upload-certs -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-upload-certs -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-init-phase-upload-certs -l skip-certificate-key-print -d '	Don\'t print the key used to encrypt the control-plane certificates'
complete -c kubeadm-init-phase-upload-certs -l upload-certs -d '	Upload control-plane certificates to the kubeadm-certs Secret'
complete -c kubeadm-init-phase-upload-certs -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-upload-certs -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

