# kubeadm-upgrade-apply-phase-preflight
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade-apply-phase-preflight.1
complete -c kubeadm-upgrade-apply-phase-preflight -l allow-experimental-upgrades -d '	Show unstable versions of Kubernetes as an upgrade alternative and allow upg…'
complete -c kubeadm-upgrade-apply-phase-preflight -l allow-release-candidate-upgrades -d '	Show release candidate versions of Kubernetes as an upgrade alternative and …'
complete -c kubeadm-upgrade-apply-phase-preflight -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-upgrade-apply-phase-preflight -l dry-run -d '	Do not change any state, just output what actions would be performed'
complete -c kubeadm-upgrade-apply-phase-preflight -s f -l force -d '	Force upgrading although some requirements might not be met'
complete -c kubeadm-upgrade-apply-phase-preflight -l ignore-preflight-errors -d '	A list of checks whose errors will be shown as warnings'
complete -c kubeadm-upgrade-apply-phase-preflight -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-apply-phase-preflight -s y -l yes -d '	Perform the upgrade and do not prompt for confirmation (non-interactive mode)'
complete -c kubeadm-upgrade-apply-phase-preflight -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-apply-phase-preflight -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

