# kubeadm-init-phase-kubelet-start
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-kubelet-start.1
complete -c kubeadm-init-phase-kubelet-start -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-kubelet-start -l cri-socket -d '	Path to the CRI socket to connect'
complete -c kubeadm-init-phase-kubelet-start -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-kubelet-start -l image-repository -d '	Choose a container registry to pull control plane images from'
complete -c kubeadm-init-phase-kubelet-start -l node-name -d '	Specify the node name'
complete -c kubeadm-init-phase-kubelet-start -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-init-phase-kubelet-start -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-kubelet-start -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

