# kubeadm-init-phase-certs
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-certs.1
complete -c kubeadm-init-phase-certs -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-certs -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

