# kubeadm-config-validate
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-config-validate.1
complete -c kubeadm-config-validate -l allow-experimental-api -d '	Allow validation of experimental, unreleased APIs'
complete -c kubeadm-config-validate -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-config-validate -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-config-validate -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-config-validate -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

