# kubeadm-join-phase-control-plane-join-all
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-join-phase-control-plane-join-all.1
complete -c kubeadm-join-phase-control-plane-join-all -l apiserver-advertise-address -d '	If the node should host a new control plane instance, the IP address the API…'
complete -c kubeadm-join-phase-control-plane-join-all -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-join-phase-control-plane-join-all -l control-plane -d '	Create a new control plane instance on this node'
complete -c kubeadm-join-phase-control-plane-join-all -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-join-phase-control-plane-join-all -l node-name -d '	Specify the node name'
complete -c kubeadm-join-phase-control-plane-join-all -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-join-phase-control-plane-join-all -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-join-phase-control-plane-join-all -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

