# kubeadm-certs-generate-csr
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-certs-generate-csr.1
complete -c kubeadm-certs-generate-csr -l cert-dir -d '	The path where to save the certificates'
complete -c kubeadm-certs-generate-csr -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-certs-generate-csr -l kubeconfig-dir -d '	The path where to save the kubeconfig file'
complete -c kubeadm-certs-generate-csr -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-certs-generate-csr -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

