# kubeadm-version
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-version.1
complete -c kubeadm-version -s o -l output -d '	Output format; available options are \'yaml\', \'json\' and \'short\' OPTIONS INHE…'
complete -c kubeadm-version -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-version -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

