# kubeadm-init-phase-preflight
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-preflight.1
complete -c kubeadm-init-phase-preflight -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-preflight -l cri-socket -d '	Path to the CRI socket to connect'
complete -c kubeadm-init-phase-preflight -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-preflight -l ignore-preflight-errors -d '	A list of checks whose errors will be shown as warnings'
complete -c kubeadm-init-phase-preflight -l image-repository -d '	Choose a container registry to pull control plane images from OPTIONS INHERI…'
complete -c kubeadm-init-phase-preflight -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-preflight -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

