# kubeadm-upgrade-node-phase-post-upgrade
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade-node-phase-post-upgrade.1
complete -c kubeadm-upgrade-node-phase-post-upgrade -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-upgrade-node-phase-post-upgrade -l dry-run -d '	Do not change any state, just output the actions that would be performed'
complete -c kubeadm-upgrade-node-phase-post-upgrade -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-node-phase-post-upgrade -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-node-phase-post-upgrade -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

