# kubeadm-init-phase-kubelet-finalize-enable-client-cert-rotation
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-kubelet-finalize-enable-client-cert-rotation.1
complete -c kubeadm-init-phase-kubelet-finalize-enable-client-cert-rotation -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-kubelet-finalize-enable-client-cert-rotation -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-kubelet-finalize-enable-client-cert-rotation -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-kubelet-finalize-enable-client-cert-rotation -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-kubelet-finalize-enable-client-cert-rotation -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

