# kubeadm-alpha
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-alpha.1
complete -c kubeadm-alpha -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-alpha -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

