# kubeadm-certs-certificate-key
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-certs-certificate-key.1
complete -c kubeadm-certs-certificate-key -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-certs-certificate-key -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

