# kubeadm-init-phase-kubelet-finalize
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-kubelet-finalize.1
complete -c kubeadm-init-phase-kubelet-finalize -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-kubelet-finalize -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

