# kubeadm-init-phase-etcd
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-etcd.1
complete -c kubeadm-init-phase-etcd -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-etcd -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

