# kubeadm-upgrade-apply-phase-upload-config-kubeadm
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade-apply-phase-upload-config-kubeadm.1
complete -c kubeadm-upgrade-apply-phase-upload-config-kubeadm -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-upgrade-apply-phase-upload-config-kubeadm -l dry-run -d '	Do not change any state, just output what actions would be performed'
complete -c kubeadm-upgrade-apply-phase-upload-config-kubeadm -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-apply-phase-upload-config-kubeadm -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-apply-phase-upload-config-kubeadm -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

