# kubeadm-init-phase-addon
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-addon.1
complete -c kubeadm-init-phase-addon -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-addon -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

