# kubeadm-config-print-init-defaults
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-config-print-init-defaults.1
complete -c kubeadm-config-print-init-defaults -l component-configs -d '	A comma-separated list for component config API objects to print the default…'
complete -c kubeadm-config-print-init-defaults -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-config-print-init-defaults -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-config-print-init-defaults -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

