# kubeadm
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm.1
complete -c kubeadm -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

