# kubeadm-certs-renew-front-proxy-client
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-certs-renew-front-proxy-client.1
complete -c kubeadm-certs-renew-front-proxy-client -l cert-dir -d '	The path where to save the certificates'
complete -c kubeadm-certs-renew-front-proxy-client -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-certs-renew-front-proxy-client -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-certs-renew-front-proxy-client -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-certs-renew-front-proxy-client -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

