# kubeadm-config-images-list
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-config-images-list.1
complete -c kubeadm-config-images-list -l allow-missing-template-keys -d '	If true, ignore any errors in templates when a field or map key is missing i…'
complete -c kubeadm-config-images-list -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-config-images-list -l feature-gates -d '	A set of key=value pairs that describe feature gates for various features'
complete -c kubeadm-config-images-list -l image-repository -d '	Choose a container registry to pull control plane images from'
complete -c kubeadm-config-images-list -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-config-images-list -s o -l output -d '	Output format'
complete -c kubeadm-config-images-list -l show-managed-fields -d '	If true, keep the managedFields when printing objects in JSON or YAML format'
complete -c kubeadm-config-images-list -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-config-images-list -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-config-images-list -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

