# kubeadm-certs-renew
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-certs-renew.1
complete -c kubeadm-certs-renew -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-certs-renew -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

