# kubeadm-certs-renew-controller-manager.conf
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-certs-renew-controller-manager.conf.1
complete -c 'kubeadm-certs-renew-controller-manager.conf' -l cert-dir -d '	The path where to save the certificates'
complete -c 'kubeadm-certs-renew-controller-manager.conf' -l config -d '	Path to a kubeadm configuration file'
complete -c 'kubeadm-certs-renew-controller-manager.conf' -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c 'kubeadm-certs-renew-controller-manager.conf' -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c 'kubeadm-certs-renew-controller-manager.conf' -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

