# kubeadm-certs-check-expiration
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-certs-check-expiration.1
complete -c kubeadm-certs-check-expiration -l allow-missing-template-keys -d '	If true, ignore any errors in templates when a field or map key is missing i…'
complete -c kubeadm-certs-check-expiration -l cert-dir -d '	The path where to save the certificates'
complete -c kubeadm-certs-check-expiration -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-certs-check-expiration -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-certs-check-expiration -s o -l output -d '	Output format'
complete -c kubeadm-certs-check-expiration -l show-managed-fields -d '	If true, keep the managedFields when printing objects in JSON or YAML format'
complete -c kubeadm-certs-check-expiration -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-certs-check-expiration -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

