# kubeadm-config-print
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-config-print.1
complete -c kubeadm-config-print -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-config-print -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-config-print -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

