# kubeadm-init-phase-control-plane-scheduler
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-control-plane-scheduler.1
complete -c kubeadm-init-phase-control-plane-scheduler -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-control-plane-scheduler -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-control-plane-scheduler -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-control-plane-scheduler -l image-repository -d '	Choose a container registry to pull control plane images from'
complete -c kubeadm-init-phase-control-plane-scheduler -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-init-phase-control-plane-scheduler -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-init-phase-control-plane-scheduler -l scheduler-extra-args -d '	A set of extra flags to pass to the Scheduler or override default ones in fo…'
complete -c kubeadm-init-phase-control-plane-scheduler -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-control-plane-scheduler -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

