# kubeadm-upgrade-diff
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade-diff.1
complete -c kubeadm-upgrade-diff -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-upgrade-diff -s c -l context-lines -d '	How many lines of context in the diff'
complete -c kubeadm-upgrade-diff -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-diff -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-diff -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

