# kubeadm-kubeconfig
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-kubeconfig.1
complete -c kubeadm-kubeconfig -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-kubeconfig -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

