# kubeadm-upgrade-apply-phase
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade-apply-phase.1
complete -c kubeadm-upgrade-apply-phase -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-apply-phase -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

