# kubeadm-config-migrate
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-config-migrate.1
complete -c kubeadm-config-migrate -l new-config -d 'In other words, the output of this command is what kubeadm actually would rea…'
complete -c kubeadm-config-migrate -l allow-experimental-api -d '	Allow migration to experimental, unreleased APIs'
complete -c kubeadm-config-migrate -l old-config -d '	Path to the kubeadm config file that is using an old API version and should …'
complete -c kubeadm-config-migrate -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-config-migrate -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-config-migrate -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

