# kubeadm-upgrade-apply-phase-upload-config
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade-apply-phase-upload-config.1
complete -c kubeadm-upgrade-apply-phase-upload-config -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-apply-phase-upload-config -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

