# kubeadm-init-phase-show-join-command
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-show-join-command.1
complete -c kubeadm-init-phase-show-join-command -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-show-join-command -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

