# kubeadm-upgrade-apply-phase-control-plane
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade-apply-phase-control-plane.1
complete -c kubeadm-upgrade-apply-phase-control-plane -l certificate-renewal -d '	Perform the renewal of certificates used by component changed during upgrades'
complete -c kubeadm-upgrade-apply-phase-control-plane -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-upgrade-apply-phase-control-plane -l dry-run -d '	Do not change any state, just output what actions would be performed'
complete -c kubeadm-upgrade-apply-phase-control-plane -l etcd-upgrade -d '	Perform the upgrade of etcd'
complete -c kubeadm-upgrade-apply-phase-control-plane -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-apply-phase-control-plane -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-upgrade-apply-phase-control-plane -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-apply-phase-control-plane -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

