# kubeadm-init-phase-kubeconfig-kubelet
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-kubeconfig-kubelet.1
complete -c kubeadm-init-phase-kubeconfig-kubelet -l apiserver-advertise-address -d '	The IP address the API Server will advertise it\'s listening on'
complete -c kubeadm-init-phase-kubeconfig-kubelet -l apiserver-bind-port -d '	Port for the API Server to bind to'
complete -c kubeadm-init-phase-kubeconfig-kubelet -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-kubeconfig-kubelet -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-kubeconfig-kubelet -l control-plane-endpoint -d '	Specify a stable IP address or DNS name for the control plane'
complete -c kubeadm-init-phase-kubeconfig-kubelet -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-kubeconfig-kubelet -l kubeconfig-dir -d '	The path where to save the kubeconfig file'
complete -c kubeadm-init-phase-kubeconfig-kubelet -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-init-phase-kubeconfig-kubelet -l node-name -d '	Specify the node name.  OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c kubeadm-init-phase-kubeconfig-kubelet -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-kubeconfig-kubelet -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

