# kubeadm-upgrade-apply-phase-kubelet-config
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade-apply-phase-kubelet-config.1
complete -c kubeadm-upgrade-apply-phase-kubelet-config -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-upgrade-apply-phase-kubelet-config -l dry-run -d '	Do not change any state, just output what actions would be performed'
complete -c kubeadm-upgrade-apply-phase-kubelet-config -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-apply-phase-kubelet-config -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-upgrade-apply-phase-kubelet-config -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-apply-phase-kubelet-config -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

