# kubeadm-token-delete
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-token-delete.1
complete -c kubeadm-token-delete -l dry-run -d '	Whether to enable dry-run mode or not'
complete -c kubeadm-token-delete -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-token-delete -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-token-delete -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

