# kubeadm-join-phase-control-plane-prepare-all
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-join-phase-control-plane-prepare-all.1
complete -c kubeadm-join-phase-control-plane-prepare-all -l apiserver-advertise-address -d '	If the node should host a new control plane instance, the IP address the API…'
complete -c kubeadm-join-phase-control-plane-prepare-all -l apiserver-bind-port -d '	If the node should host a new control plane instance, the port for the API S…'
complete -c kubeadm-join-phase-control-plane-prepare-all -l certificate-key -d '	Use this key to decrypt the certificate secrets uploaded by init'
complete -c kubeadm-join-phase-control-plane-prepare-all -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-join-phase-control-plane-prepare-all -l control-plane -d '	Create a new control plane instance on this node'
complete -c kubeadm-join-phase-control-plane-prepare-all -l discovery-file -d '	For file-based discovery, a file or URL from which to load cluster informati…'
complete -c kubeadm-join-phase-control-plane-prepare-all -l discovery-token -d '	For token-based discovery, the token used to validate cluster information fe…'
complete -c kubeadm-join-phase-control-plane-prepare-all -l discovery-token-ca-cert-hash -d '	For token-based discovery, validate that the root CA public key matches this…'
complete -c kubeadm-join-phase-control-plane-prepare-all -l discovery-token-unsafe-skip-ca-verification -d '	For token-based discovery, allow joining without --discovery-token-ca-cert-h…'
complete -c kubeadm-join-phase-control-plane-prepare-all -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-join-phase-control-plane-prepare-all -l node-name -d '	Specify the node name'
complete -c kubeadm-join-phase-control-plane-prepare-all -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-join-phase-control-plane-prepare-all -l tls-bootstrap-token -d '	Specify the token used to temporarily authenticate with the Kubernetes Contr…'
complete -c kubeadm-join-phase-control-plane-prepare-all -l token -d '	Use this token for both discovery-token and tls-bootstrap-token when those v…'
complete -c kubeadm-join-phase-control-plane-prepare-all -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-join-phase-control-plane-prepare-all -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

