# kubeadm-upgrade-node-phase-preflight
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-upgrade-node-phase-preflight.1
complete -c kubeadm-upgrade-node-phase-preflight -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-upgrade-node-phase-preflight -l ignore-preflight-errors -d '	A list of checks whose errors will be shown as warnings'
complete -c kubeadm-upgrade-node-phase-preflight -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-node-phase-preflight -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

