# kubeadm-init-phase-wait-control-plane
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-init-phase-wait-control-plane.1
complete -c kubeadm-init-phase-wait-control-plane -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-wait-control-plane -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

