# kubeadm-join-phase-control-plane-join
# Autogenerated from man page /opt/homebrew/share/man/man1/kubeadm-join-phase-control-plane-join.1
complete -c kubeadm-join-phase-control-plane-join -l rootfs -d '	The path to the \'real\' host root filesystem'
complete -c kubeadm-join-phase-control-plane-join -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

