# lto-dump-15
# Autogenerated from man page /opt/homebrew/share/man/man1/lto-dump-15.1
complete -c lto-dump-15 -o list -d 'Dumps list of details of functions and variables'
complete -c lto-dump-15 -o demangle -d 'Dump the demangled output'
complete -c lto-dump-15 -o defined-only -d 'Dump only the defined symbols'
complete -c lto-dump-15 -o print-value -d 'Dump initial values of the variables'
complete -c lto-dump-15 -o name-sort -d 'Sort the symbols alphabetically'
complete -c lto-dump-15 -o size-sort -d 'Sort the symbols according to size'
complete -c lto-dump-15 -o reverse-sort -d 'Dump the symbols in reverse order'
complete -c lto-dump-15 -o no-sort -d 'Dump the symbols in order of occurrence'
complete -c lto-dump-15 -o symbol -d 'Dump the details of specific symbol'
complete -c lto-dump-15 -o objects -d 'Dump the details of \\s-1LTO\\s0 objects'
complete -c lto-dump-15 -o type-stats -d 'Dump the statistics of tree types'
complete -c lto-dump-15 -o tree-stats -d 'Dump the statistics of trees'
complete -c lto-dump-15 -o gimple-stats -d 'Dump the statistics of gimple statements'
complete -c lto-dump-15 -o dump-level -d 'For deciding the optimization level of body'
complete -c lto-dump-15 -o dump-body -d 'Dump the specific gimple body'

