# netbiosd
# Autogenerated from man page /usr/share/man/man8/netbiosd.8
complete -c netbiosd -o dump-packets -d 'Pretty-print all sent and received NetBIOS packets to the output log'
complete -c netbiosd -o help -d 'Prints a usage message and exits'
complete -c netbiosd -o max-refresh -d 'Maximum time (in seconds) between searches to refresh the workgroup list'
complete -c netbiosd -o min-refresh -d 'Minimum time (in seconds) between searches to refresh the workgroup list'

