# newfs_fskit
# Autogenerated from man page /usr/share/man/man8/newfs_fskit.8
complete -c newfs_fskit -l progress -d 'causes newfs_fskit to display a progres bar during the creation operation'
complete -c newfs_fskit -s t -d 'Use the FSKit Module named fstype to perform the creation operation'

