# nlcontrol
# Autogenerated from man page /usr/share/man/man8/nlcontrol.8
complete -c nlcontrol -o domain -d 'Domain name'
complete -c nlcontrol -o help -d 'Prints a usage message and exits'
complete -c nlcontrol -o server -d 'Server name'

