# numfmt
# Autogenerated from man page /opt/homebrew/share/man/man1/numfmt.1
complete -c numfmt -l delimiter -d 'use X instead of whitespace for field delimiter'
complete -c numfmt -l 'zero-terminated\\X\'tty' -d 'line delimiter is NUL, not newline'
complete -c numfmt -s M -d 'from first to M\'th field (inclusive)'
complete -c numfmt -s '>' -d '$ numfmt --to=iec 2048'

