# pkg_admin
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/pkg_admin.1
complete -c pkg_admin -s b -d 'Print only the base names when matching package names for lsall and lsbest'
complete -c pkg_admin -s C -d 'Read the configuration file from config instead of the system default'
complete -c pkg_admin -s d -d 'Set lsdir as the path to the directory in which to find matching package name…'
complete -c pkg_admin -s K -d 'Override the value of the PKG_DBDIR configuration option with the value pkg_d…'
complete -c pkg_admin -s q -d 'Perform checks in a quiet manner.  In normal operation, pkg_admin prints a \\&'
complete -c pkg_admin -s S -d 'Set the shell glob pattern for package suffixes when matching package names f…'
complete -c pkg_admin -s s -d 'Set the shell glob pattern for package suffixes when matching package names f…'
complete -c pkg_admin -s V -d 'Print version number and exit'
complete -c pkg_admin -s v -d 'Be more verbose'

