# pkg_delete
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/pkg_delete.1
complete -c pkg_delete -s A -d 'Recursively remove all automatically installed packages that were needed by t…'
complete -c pkg_delete -s D -d 'If a deinstallation script exists for a given package, do not execute it'
complete -c pkg_delete -s F -d 'Any pkg-name given will be interpreted as pathname which is subsequently tran…'
complete -c pkg_delete -s f -d 'Force removal of the package, even if a dependency is recorded or the deinsta…'
complete -c pkg_delete -o ff -d 'Force removal of the package, even if the package is marked as a preserved pa…'
complete -c pkg_delete -s K -d 'Override the value of the PKG_DBDIR configuration option with the value pkg_d…'
complete -c pkg_delete -s k -d 'Silently skip all packages that are marked as preserved'
complete -c pkg_delete -s N -d 'Remove the package\'s registration and its entries from the package database, …'
complete -c pkg_delete -s n -d 'Don\'t actually deinstall a package, just report the steps that would be taken'
complete -c pkg_delete -s O -d 'Only delete the package\'s entries from the package database; do not touch the…'
complete -c pkg_delete -s P -d 'Prefix all file and directory names with destdir'
complete -c pkg_delete -s p -d 'Set prefix as the directory in which to delete files from any installed packa…'
complete -c pkg_delete -s R -d 'Recursively remove all packages that were needed by the given packages and ar…'
complete -c pkg_delete -s r -d 'Recursively remove all packages that require one of the packages given'
complete -c pkg_delete -s V -d 'Print version number and exit'
complete -c pkg_delete -s v -d 'Turn on verbose output'

