# pkg_add
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/pkg_add.1
complete -c pkg_add -s A -d 'Mark package as installed automatically, as dependency of another package'
complete -c pkg_add -s C -d 'Read the configuration file from config instead of the system default'
complete -c pkg_add -s D -d 'Force updating even if the dependencies of depending packages are not satisfi…'
complete -c pkg_add -s f -d 'Force installation to proceed even if prerequisite packages are not installed…'
complete -c pkg_add -s h -d 'Display help and exit'
complete -c pkg_add -s I -d 'If an installation script exists for a given package, do not execute it'
complete -c pkg_add -s K -d 'Override the value of the PKG_DBDIR configuration option with the value pkg_d…'
complete -c pkg_add -s m -d 'Override the machine architecture returned by uname with machine'
complete -c pkg_add -s n -d 'Don\'t actually install a package, just report the steps that would be taken i…'
complete -c pkg_add -s P -d 'Prefix all file and directory names with destdir'
complete -c pkg_add -s p -d 'Override the prefix stored in the package with prefix'
complete -c pkg_add -s R -d 'Do not record the installation of a package.  This implies I'
complete -c pkg_add -s U -d 'Replace an already installed version from a package.  Implies u'
complete -c pkg_add -s u -d 'If the package that\'s being installed is already installed, an update is perf…'
complete -c pkg_add -s V -d 'Print version number and exit'
complete -c pkg_add -s v -d 'Turn on verbose output'

