# prl_convert
# Autogenerated from man page /usr/local/share/man/man8/prl_convert.8
complete -c prl_convert -l estimate -d 'Estimate the amount of disk space required to perform the conversion'
complete -c prl_convert -l dst -d 'Specify the destination directory'
complete -c prl_convert -l force -d 'Ignore noncritical errors when converting a virtual machine or hard disk to t…'
complete -c prl_convert -l allow-no-os -d 'Allow to convert data disks or disks whose operating system cannot be detected'
complete -c prl_convert -l allow-no-hdd -d 'Allow to convert virtual machines that have no virtual hard disks to the Para…'
complete -c prl_convert -l no-reconfig -d 'Skip the reconfiguration step of the resulting virtual machine'
complete -c prl_convert -l no-src-check -d 'Don\'t check the state of the source virtual disk(s)'
complete -c prl_convert -l no-hibernate-check -d 'Do not check whether the guest operating system is hibernated'
complete -c prl_convert -s r -l reg -d 'Register the resulting virtual machine in Parallels Desktop (y by default)'
complete -c prl_convert -l vbox-home -d 'Specify the path to the directory storing the virtual machine configuration f…'
complete -c prl_convert -l os-files -d 'Set the path to the operating system installation files'
complete -c prl_convert -l err-code -d 'Show error codes instead of text messages'

