# prlcopy
# Autogenerated from man page /usr/local/share/man/man8/prlcopy.8
complete -c prlcopy -l vm -d 'Execute action in the specified virtual machine'
complete -c prlcopy -l user -d 'Performs the action under the specified user'
complete -c prlcopy -s r -l exec -d 'Executes a script after the upload'

