# prlexec
# Autogenerated from man page /usr/local/share/man/man8/prlexec.8
complete -c prlexec -l vm -d 'Specifies the virtual machine in which the command is executed'
complete -c prlexec -l user -d 'Specifies which user the command is executed under'
complete -c prlexec -l password -d 'Provides the password for the current logged-in user or the user specified wi…'

