# quitreally
# Autogenerated from man page /usr/share/man/man8/quitreally.8
complete -c quitreally -l -status -d 'Returns information about the applications which have exited and left behind …'
complete -c quitreally -l inspect -d 'Returns information about the application specified by Ar APP'
complete -c quitreally -l visible -d 'Returns whether the given application is visible or not'

