# ruby-build
# Autogenerated from man page /opt/homebrew/share/man/man1/ruby-build.1
complete -c ruby-build -s l -l list
complete -c ruby-build -l definitions
complete -c ruby-build -l version
complete -c ruby-build -s d -l dir
complete -c ruby-build -s v -l verbose
complete -c ruby-build -s p -l patch
complete -c ruby-build -s k -l keep
complete -c ruby-build -s 4 -l ipv4
complete -c ruby-build -s 6 -l ipv6

