# smbd
# Autogenerated from man page /usr/share/man/man8/smbd.8
complete -c smbd -o help -d 'Prints a usage message and exits'
complete -c smbd -o ports -d 'The service will listen on each of the TCP ports specified in the comma-separ…'
complete -c smbd -o no-symlinks -d 'In normal operation, smbd will respond to client symlink requests but will ne…'

