# stdbuf
# Autogenerated from man page /opt/homebrew/share/man/man1/stdbuf.1
complete -c stdbuf -l input -d 'adjust standard input stream buffering'
complete -c stdbuf -l output -d 'adjust standard output stream buffering'
complete -c stdbuf -l error -d 'adjust standard error stream buffering'

