# stz
# Autogenerated from man page /usr/share/man/man1/stz.1
complete -c stz -l hash-type -d 'Set the hash type for verification'
complete -c stz -l hash-size -d 'Hash the archive\'s contents over each given byte-sized interval and verify th…'
complete -c stz -l hashes-file -d 'Path to UTF8-encoded file containing the hashes, in order and one line per ha…'

