# typst-init
# Autogenerated from man page /opt/homebrew/share/man/man1/typst-init.1
complete -c typst-init -l package-path -d 'Custom path to local packages, defaults to system-dependent location '
complete -c typst-init -l package-cache-path -d 'Custom path to package cache, defaults to system-dependent location '
complete -c typst-init -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

