# typst
# Autogenerated from man page /opt/homebrew/share/man/man1/typst.1
complete -c typst -l color -d 'Whether to use color.  When set to `auto` if the terminal to supports it '
complete -c typst -l cert -d 'Path to a custom CA certificate to use when making network requests '
complete -c typst -s h -l help -d 'Print help'
complete -c typst -s V -l version -d 'Print version SUBCOMMANDS'

