# usage
# Autogenerated from man page /opt/homebrew/share/man/man1/usage.1
complete -c usage -l usage-spec -d 'Outputs a `usage. kdl` spec for this CLI itself ARGUMENTS'
complete -c usage -s h -d 'Show help'
complete -c usage -l help -d 'Show help Arguments: <ARGS> Arguments to pass to script USAGE COMPLETE-WORD G…'
complete -c usage -s f -l file -d 'Usage spec file or script with usage shebang'
complete -c usage -s s -l spec -d 'Raw string spec input'
complete -c usage -l cword -d 'Current word index'
complete -c usage -l shell
complete -c usage -l cache-key -d 'A cache key to use for storing the results of calling the CLI with --usage-cmd'
complete -c usage -l include-bash-completion-lib -d 'Include https://github. com/scop/bash-completion'
complete -c usage -l usage-bin -d 'Override the bin used for calling back to usage-cli'
complete -c usage -l usage-cmd -d 'A command which generates a usage spec e. g'
complete -c usage -l out-file -d 'File path where the generated Fig spec will be saved'
complete -c usage -s o -d 'Output file path (defaults to stdout)'
complete -c usage -l section -d 'Manual section number (default: 1)'
complete -c usage -s m -l multi -d 'Render each subcommand as a separate markdown file'
complete -c usage -l html-encode -d 'Escape HTML in markdown'
complete -c usage -l out-dir -d 'Output markdown files to this directory (required when using --multi)'
complete -c usage -l replace-pre-with-code-fences -d 'Replace `<pre>` tags with markdown code fences'
complete -c usage -l url-prefix -d 'Prefix to add to all URLs USAGE LINT Lint a usage spec file for common issues'
complete -c usage -l format -d 'Output format'
complete -c usage -s W -l warnings-as-errors -d 'Treat warnings as errors Arguments: <FILE> A usage spec file to lint USAGE PO…'

