# usdcat
# Autogenerated from man page /usr/share/man/man1/usdcat.1
complete -c usdcat -s h -l help -d 'Prints out a help message and exits'
complete -c usdcat -s o -l output -d 'Write a single input file to this output file instead of stdout'
complete -c usdcat -l usdFormat -d 'Use this underlying file format for output files with the extension \'usd\''
complete -c usdcat -s l -l loadOnly -d 'Attempt to load the specified input files and report \'OK\' or \'ERR\' for each o…'
complete -c usdcat -s f -l flatten -d 'Compose stages with the input files as root layers'
complete -c usdcat -l flattenLayerStack -d 'Flatten the layer stack with the given root layer, and write out the results'
complete -c usdcat -l skipSourceFileComment -d 'If --flatten is specified, skip adding a comment regarding the source of the …'
complete -c usdcat -l mask -d 'Limit stage population to these prims, their descendants and ancestors'
complete -c usdcat -l layerMetadata -d 'Load only layer metadata in the USD file'
complete -c usdcat -l version -d 'Display program version information and exit'

