# usdcrush
# Autogenerated from man page /usr/share/man/man1/usdcrush.1
complete -c usdcrush -s h -l help -d 'Prints out a help message and exits'
complete -c usdcrush -s o -l out -d 'The output file to write to.  This is required'
complete -c usdcrush -s c -l compatibility -d 'Controls how compatible the output file is with different platforms and OpenU…'
complete -c usdcrush -s t -l textureQuality -d 'A value that acts as a hint to texture compressors'
complete -c usdcrush -l version -d 'Display program version information and exits'

