# usdchecker
# Autogenerated from man page /usr/share/man/man1/usdchecker.1
complete -c usdchecker -s h -l help -d 'Prints out a help message and exits'
complete -c usdchecker -s o -l out -d 'The file to which all the failed checks are output'
complete -c usdchecker -s s -l skipVariants -d 'If specified, only the prims that are present in the default (i. e'
complete -c usdchecker -s p -l rootPackageOnly -d 'Check only the specifiedpackage'
complete -c usdchecker -l noAssetChecks -d 'If specified, do NOT perform extra checks to help ensure the stage or package…'
complete -c usdchecker -l arkit -d 'Check if the given USD stage is compatible with RealityKit\'s support of USD'
complete -c usdchecker -s d -l dumpRules -d 'Prints the enumerated set of rules being checked for the given set of options'
complete -c usdchecker -s v -l verbose -d 'Enable verbose output mode'
complete -c usdchecker -s t -l strict -d 'Return failure code even if only warnings are issued, for stricter compliance'
complete -c usdchecker -l variants -d 'List of variantSets to validate'
complete -c usdchecker -l variantSets -d 'List of \',\' separated variantSet:variant pairs to validate'
complete -c usdchecker -l disableVariantValidationLimit -d 'Disable the limit set to restrict the number of variants validation  calls'
complete -c usdchecker -l version -d 'Display program version information and exits'

