# usdextract
# Autogenerated from man page /usr/share/man/man1/usdextract.1
complete -c usdextract -s h -l help -d 'Prints out a help message and exits'
complete -c usdextract -s o -l out -d 'Extracts the file to the given directory'
complete -c usdextract -l version -d 'Display program version information and exits'

