# usdrecord
# Autogenerated from man page /usr/share/man/man1/usdrecord.1
complete -c usdrecord -s h -l help -d 'Prints out a help message and exits'
complete -c usdrecord -l mask -d 'Limit stage population to these prims, their descendants and ancestors'
complete -c usdrecord -l purposes -d 'Specify which UsdGeomImageable purposes should be included in the renders'
complete -c usdrecord -l sessionLayer -d 'If specified, the stage will be opened with the \'sessionLayer\' in place of th…'
complete -c usdrecord -l disableGpu -d 'Indicates if the GPU should not be used for rendering'
complete -c usdrecord -l disableCameraLight -d 'Indicates if the default camera lights should not be used for rendering'
complete -c usdrecord -l cam -l camera -d 'Which camera to use - may be given as either just the camera\'s prim name (i'
complete -c usdrecord -s d -l defaultTime -d 'Explicitly operate at the Default time code (the default behavior is to opera…'
complete -c usdrecord -s f -l frames -d 'Specify FrameSpec(s) of the time codes to operate on'
complete -c usdrecord -s c -l complexity -d 'The level of refinement to use.  Low is the default'
complete -c usdrecord -s r -l renderer -d 'Hydra renderer plugin to use when generating images'
complete -c usdrecord -s w -l imageWidth -d 'The width of the output image'
complete -c usdrecord -l enableDomeLightVisibility -l domeLightCameraVisibility -d 'Show the dome light background in the rendered output'
complete -c usdrecord -l rp -l renderPassPrimPath -d 'Specify the Render Pass Prim to use to render the given usdFile'
complete -c usdrecord -l rs -l renderSettingsPrimPath -d 'Specifies the Render Settings Prim to use to render the given usdFile'
complete -c usdrecord -l version -d 'Display program version information and exits.  EXAMPLES usdrecord input'

