# usdtree
# Autogenerated from man page /usr/share/man/man1/usdtree.1
complete -c usdtree -s h -l help -d 'Prints out a help message and exits'
complete -c usdtree -l unloaded -d 'Payloads are not loaded when this is specified'
complete -c usdtree -s a -l attributes -d 'Display authored attributes'
complete -c usdtree -s m -l metadata -d 'Display authored metadata'
complete -c usdtree -s s -l simple -d 'Only display prim names: no specifier, kind or active state'
complete -c usdtree -s f -l flatten -d 'Compose the stage with the input file as the root layer and write the flatten…'
complete -c usdtree -l flattenLayerStack -d 'Flatten the layer stack with the given root layer'
complete -c usdtree -l mask -d 'Limit stage population to these prims, their descendants and ancestors'
complete -c usdtree -l version -d 'Display program version information and exits.  EXAMPLES usdtree input'

