# usdzip
# Autogenerated from man page /usr/share/man/man1/usdzip.1
complete -c usdzip -s h -l help -d 'Prints out a help message and exits'
complete -c usdzip -s r -l recurse -d 'If specified, files in sub-directories are recursively added to the package'
complete -c usdzip -s a -l asset -d 'Resolvable asset path pointing to the root layer of the asset to be isolated …'
complete -c usdzip -o arkitAsset -d 'Similar to the --asset option, the --arkitAsset option packages all of the de…'
complete -c usdzip -s c -l checkCompliance -d 'Perform compliance checking of the input files'
complete -c usdzip -s l -l list -d 'List contents of the specified usdz file'
complete -c usdzip -s d -l dump -d 'Dump contents of the specified usdz file'
complete -c usdzip -l version -d 'Display program version information and exits.  EXAMPLES usdzip output'

