# xcresulttool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xcresulttool.1
complete -c xcresulttool -l schema -d 'Prints output format as JSON Schema'
complete -c xcresulttool -l output-path -d 'Output path for the exported file or directory'
complete -c xcresulttool -l test-id -d 'Provides the test identifier URL (or identifier string) that references a test'
complete -c xcresulttool -l compact -d 'Provides the command output in a compact format'
complete -c xcresulttool -l format -d 'Controls output format'
complete -c xcresulttool -l id -d 'Provides the desired object\'s ID (hash)'
complete -c xcresulttool -l type -d 'Used by export to identify whether to export the given data as a file or dire…'
complete -c xcresulttool -l only-failures -d 'Export only those attachments that are associated with test failures'
complete -c xcresulttool -l summary -d 'Include the differential summary info in the output'
complete -c xcresulttool -l test-failures -d 'Include the differential test failures info in the output'
complete -c xcresulttool -l tests -d 'Include the differential tests info in the output'
complete -c xcresulttool -l build-warnings -d 'Include the differential build warnings info in the output'
complete -c xcresulttool -o resultBundlePath -d ' where PATH is the desired path ending with . xcresult.  COMMANDS'
complete -c xcresulttool -l schema-version -d 'Specifies schema version in major. minor. patch format'
complete -c xcresulttool -l path -d 'Path to the result bundle'
complete -c xcresulttool -l analyzer-issues -d 'Include the differential analyzer issues info in the output'

