# xctest
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xctest.1
complete -c xctest -o XCTest -d 'This flag specifies an optional list of test identifiers to run'

