# clai.zsh - clai shell integration for Zsh
# Generated by: clai init zsh
#
# Features:
#   1. Auto-extract suggested commands from output (Tab to accept)
#   2. Auto-diagnose errors with Claude Code
#   3. Voice mode with ` prefix (fast with daemon)
#
# Configuration (set these BEFORE sourcing):
#   CLAI_AUTO_DIAGNOSE=true   # Auto-diagnose on errors (default: true)
#   CLAI_AUTO_EXTRACT=true    # Auto-extract commands (default: true)
#   CLAI_AUTO_DAEMON=true     # Auto-start daemon for fast voice (default: true)

# ============================================
# Configuration
# ============================================

: ${CLAI_AUTO_DIAGNOSE:=true}
: ${CLAI_AUTO_EXTRACT:=true}
: ${CLAI_AUTO_DAEMON:=true}
: ${CLAI_CACHE:="$HOME/.cache/clai"}

# Ensure cache directory exists
mkdir -p "$CLAI_CACHE"

# Export for child processes
export CLAI_CACHE

# Files
_AI_SUGGEST_FILE="$CLAI_CACHE/suggestion"
_AI_LAST_OUTPUT="$CLAI_CACHE/last_output"

# ============================================
# Feature 1: Command Suggestion
# ============================================

# Show suggestion hint in right prompt when available
_ai_update_rprompt() {
    if [[ -s "$_AI_SUGGEST_FILE" ]]; then
        local suggestion=$(cat "$_AI_SUGGEST_FILE")
        if [[ -n "$suggestion" ]]; then
            RPROMPT="%F{242}→ $suggestion%f"
        else
            RPROMPT=""
        fi
    else
        RPROMPT=""
    fi
}

# ZLE widget: Accept suggestion with Tab (when buffer is empty)
_ai_accept_suggestion() {
    if [[ -z "$BUFFER" && -s "$_AI_SUGGEST_FILE" ]]; then
        local suggestion=$(cat "$_AI_SUGGEST_FILE")
        if [[ -n "$suggestion" ]]; then
            BUFFER="$suggestion"
            CURSOR=${#BUFFER}
            # Clear the suggestion after accepting
            > "$_AI_SUGGEST_FILE"
            RPROMPT=""
            zle redisplay
            return
        fi
    fi
    # Default behavior: normal tab completion
    zle expand-or-complete
}
zle -N _ai_accept_suggestion

# ZLE widget: Clear suggestion with Escape
_ai_clear_suggestion() {
    > "$_AI_SUGGEST_FILE"
    RPROMPT=""
    zle redisplay
}
zle -N _ai_clear_suggestion

# Bind keys
bindkey '^I' _ai_accept_suggestion    # Tab
bindkey '^[' _ai_clear_suggestion     # Escape

# ============================================
# Feature 3: Voice Mode
# ============================================
# When activated, the next Enter press will run the input through voice conversion
# This works with speech-to-text tools like Wispr Flow that use the same hotkey
#
# Use ` prefix for voice input (e.g., "`list all files")
# The ` prefix is intercepted by ZLE before shell evaluation

_AI_VOICE_MODE=false

# ZLE widget: Enter voice mode
_ai_enter_voice_mode() {
    _AI_VOICE_MODE=true
    RPROMPT="%F{magenta}🎤 Voice mode%f"
    zle redisplay
}
zle -N _ai_enter_voice_mode

# ZLE widget: Execute with voice conversion if in voice mode or ` prefix
_ai_voice_accept_line() {
    # Check for ` prefix (voice input marker)
    # Intercepted by ZLE before shell evaluation, so backtick is safe
    if [[ "$BUFFER" == '`'* && ${#BUFFER} -gt 1 ]]; then
        local voice_input="${BUFFER#\`}"  # Remove the ` prefix
        voice_input="${voice_input## }"   # Remove leading space if any
        BUFFER=""
        zle redisplay

        # Run voice conversion and show result
        echo ""
        echo "🎤 Converting: $voice_input"
        local cmd=$(clai voice "$voice_input" 2>/dev/null)
        if [[ -n "$cmd" ]]; then
            echo "→ $cmd"
            # Suggestion is cached by clai voice; Tab to accept
        fi
        zle reset-prompt
        return
    fi

    # Check for explicit voice mode
    if [[ "$_AI_VOICE_MODE" == "true" && -n "$BUFFER" ]]; then
        # Convert the buffer through voice command
        _AI_VOICE_MODE=false
        RPROMPT=""
        local voice_input="$BUFFER"
        BUFFER=""
        zle redisplay

        # Run voice conversion and show result
        echo ""
        echo "🎤 Converting: $voice_input"
        local cmd=$(clai voice "$voice_input" 2>/dev/null)
        if [[ -n "$cmd" ]]; then
            echo "→ $cmd"
            # Suggestion is cached by clai voice; Tab to accept
        fi
        zle reset-prompt
        return
    fi
    # Normal accept-line behavior
    _AI_VOICE_MODE=false
    zle accept-line
}
zle -N _ai_voice_accept_line

# ZLE widget: Cancel voice mode with Escape
_ai_cancel_voice_mode() {
    if [[ "$_AI_VOICE_MODE" == "true" ]]; then
        _AI_VOICE_MODE=false
        _ai_update_rprompt
        zle redisplay
        return
    fi
    # Default escape behavior
    _ai_clear_suggestion
}
zle -N _ai_cancel_voice_mode

# Bind Enter to voice-aware accept
bindkey '^M' _ai_voice_accept_line    # Enter

# Bind Ctrl+V for voice mode (Cmd+Ctrl doesn't produce a terminal sequence)
# Users can rebind this or use their speech-to-text tool's hotkey
bindkey '^X^V' _ai_enter_voice_mode   # Ctrl+X Ctrl+V

# Override escape to also cancel voice mode
bindkey '^[' _ai_cancel_voice_mode    # Escape

# ============================================
# Feature 2: Auto Error Diagnosis
# ============================================

# Track command before execution
_ai_preexec() {
    _AI_LAST_CMD="$1"
    _AI_CMD_START=$EPOCHSECONDS
}

# Check result after execution
_ai_precmd() {
    local exit_code=$?

    # Update prompt with any suggestions
    _ai_update_rprompt

    # Auto-diagnose if enabled and command failed
    if [[ "$CLAI_AUTO_DIAGNOSE" == "true" &&
          $exit_code -ne 0 &&
          -n "$_AI_LAST_CMD" &&
          "$_AI_LAST_CMD" != "ai-fix"* &&
          "$_AI_LAST_CMD" != "clai"* &&
          "$_AI_LAST_CMD" != _ai_* ]]; then

        echo ""
        echo -e "\033[38;5;214m⚡ Analyzing error...\033[0m"

        # Run diagnosis
        clai diagnose "$_AI_LAST_CMD" "$exit_code" 2>/dev/null
    fi

    # Cleanup
    unset _AI_LAST_CMD _AI_CMD_START
}

# Register hooks
autoload -U add-zsh-hook
add-zsh-hook preexec _ai_preexec
add-zsh-hook precmd _ai_precmd

# ============================================
# Output Capture (via wrapper function)
# ============================================

# Wrap command execution to capture output
# Usage: run <command> - captures output and extracts suggestions
run() {
    # Run command, capture output, pass through clai extract
    "$@" 2>&1 | clai extract
    return ${pipestatus[1]}  # Return original command's exit code
}

# ============================================
# Manual Commands
# ============================================

# Manually diagnose last command
ai-fix() {
    local cmd="${1:-$(fc -ln -1)}"
    clai diagnose "$cmd" "1"
}

# Ask Claude anything with terminal context
ai() {
    if [[ -z "$1" ]]; then
        echo "Usage: ai \"your question\""
        return 1
    fi

    local recent_cmds=$(fc -ln -5 2>/dev/null | tr '\n' ';')
    clai ask --context "$recent_cmds" "$@"
}

# Convert voice/natural language to terminal command
voice() {
    if [[ -z "$1" ]]; then
        echo "Usage: voice \"natural language description\""
        return 1
    fi

    clai voice "$@"
}

# Toggle auto-diagnose
ai-toggle() {
    if [[ "$CLAI_AUTO_DIAGNOSE" == "true" ]]; then
        export CLAI_AUTO_DIAGNOSE=false
        echo "Auto-diagnose: OFF"
    else
        export CLAI_AUTO_DIAGNOSE=true
        echo "Auto-diagnose: ON"
    fi
}

# ============================================
# Daemon Management
# ============================================

# Start daemon in background for fast voice responses
_ai_ensure_daemon() {
    if [[ "$CLAI_AUTO_DAEMON" == "true" ]]; then
        # Check if daemon is running, start if not (silently in background)
        (clai daemon start >/dev/null 2>&1 &)
    fi
}

# Daemon control commands
ai-daemon() {
    case "$1" in
        start)
            clai daemon start
            ;;
        stop)
            clai daemon stop
            ;;
        status)
            clai daemon status
            ;;
        restart)
            clai daemon stop
            clai daemon start
            ;;
        *)
            echo "Usage: ai-daemon {start|stop|status|restart}"
            echo "  Manages the background Claude daemon for fast voice responses"
            ;;
    esac
}

# ============================================
# Startup
# ============================================

if [[ -o interactive ]]; then
    # Start daemon if enabled
    _ai_ensure_daemon

    echo -e "\033[2m🤖 clai loaded. Commands: ai-fix, ai, voice, ai-daemon | \` prefix for voice mode\033[0m"
fi
